title: Homey Tuya Zigbee Ultimate
description: Community-driven Tuya Zigbee devices support for Homey
baseurl: ""
url: "https://your-username.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - node_modules/
  - scripts/
  - test/
  - "*.js"
  - "*.json"
  - Gemfile
  - Gemfile.lock
  - README.md

include:
  - public/

collections:
  drivers:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "drivers"
    values:
      layout: "driver"