# MEGA ULTIMATE ENHANCED - 2025-08-07T16:33:45.007Z
# Workflow amélioré avec liens corrigés et fonctionnalités étendues

name: Version Functional Release Management

on:
  push:
    branches: [master]
    paths:
      - 'tools/version-functional-release.js'
      - 'releases/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create functional release for'
        required: false
        default: 'all'
      force_update:
        description: 'Force update all versions'
        required: false
        default: 'false'

jobs:
  version-functional-release:
    runs-on: ubuntu-latest
    name: Version Functional Release Management
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install
          echo "Dependencies installed successfully"
          
      - name: Run version functional release manager
        id: version_manager
        run: |
          echo "Running Version Functional Release Manager..."
          node tools/version-functional-release.js
          
          # Load release information
          if [ -f "releases/release-1.3.0.json" ]; then
            CURRENT_RELEASE=$(cat releases/release-1.3.0.json)
            echo "current_release<<EOF" >> $GITHUB_OUTPUT
            echo "$CURRENT_RELEASE" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
          
          if [ -f "releases/release-1.2.0.json" ]; then
            PREVIOUS_RELEASE=$(cat releases/release-1.2.0.json)
            echo "previous_release<<EOF" >> $GITHUB_OUTPUT
            echo "$PREVIOUS_RELEASE" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
          
          if [ -f "releases/release-1.1.0.json" ]; then
            LEGACY_RELEASE=$(cat releases/release-1.1.0.json)
            echo "legacy_release<<EOF" >> $GITHUB_OUTPUT
            echo "$LEGACY_RELEASE" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
          
          echo "Version functional release manager completed"
          
      - name: Verify functional components
        id: verify_components
        run: |
          echo "Verifying functional components..."
          
          # Create verification script
          cat > tools/verify-functional-components.js << 'EOF'
          const fs = require('fs');
          const path = require('path');
          
          // Load version configuration
          const versionConfig = require('./version-functional-release.js').VERSION_CONFIG;
          
          const verificationResults = {};
          
          Object.keys(versionConfig).forEach(versionKey => {
            const version = versionConfig[versionKey];
            console.log(`Verifying components for version ${version.version}`);
            
            const verification = {
              version: version.version,
              codename: version.codename,
              components_verified: [],
              components_missing: [],
              functionality_score: 0
            };
            
            // Verify functional components
            version.functional_components.forEach(component => {
              const componentPath = `tools/${component}`;
              const workflowPath = `.github/workflows/${component}`;
              
              if (fs.existsSync(componentPath) || fs.existsSync(workflowPath)) {
                verification.components_verified.push(component);
              } else {
                verification.components_missing.push(component);
              }
            });
            
            // Calculate functionality score
            verification.functionality_score = Math.round(
              (verification.components_verified.length / version.functional_components.length) * 100
            );
            
            verificationResults[versionKey] = verification;
            
            console.log(`Version ${version.version}: ${verification.components_verified.length}/${version.functional_components.length} components verified (${verification.functionality_score}%)`);
          });
          
          // Save verification results
          fs.writeFileSync('releases/functional-verification.json', JSON.stringify(verificationResults, null, 2));
          
          console.log('Functional components verification completed');
          
          // Output for GitHub Actions
          Object.keys(verificationResults).forEach(versionKey => {
            const result = verificationResults[versionKey];
            console.log(`::set-output name=${versionKey}_score::${result.functionality_score}`);
            console.log(`::set-output name=${versionKey}_verified::${result.components_verified.length}`);
            console.log(`::set-output name=${versionKey}_missing::${result.components_missing.length}`);
          });
          EOF
          
          # Run verification
          node tools/verify-functional-components.js
          
      - name: Generate release documentation
        id: generate_docs
        run: |
          echo "Generating release documentation..."
          
          # Create documentation generator
          cat > tools/generate-release-docs.js << 'EOF'
          const fs = require('fs');
          const path = require('path');
          
          // Load verification results
          const verificationResults = JSON.parse(fs.readFileSync('releases/functional-verification.json', 'utf8'));
          
          // Generate comprehensive documentation
          const docs = {
            timestamp: new Date().toISOString(),
            versions: verificationResults,
            summary: {
              total_versions: Object.keys(verificationResults).length,
              fully_functional: 0,
              mostly_functional: 0,
              partially_functional: 0,
              non_functional: 0
            }
          };
          
          Object.keys(verificationResults).forEach(versionKey => {
            const result = verificationResults[versionKey];
            if (result.functionality_score >= 90) {
              docs.summary.fully_functional++;
            } else if (result.functionality_score >= 70) {
              docs.summary.mostly_functional++;
            } else if (result.functionality_score >= 50) {
              docs.summary.partially_functional++;
            } else {
              docs.summary.non_functional++;
            }
          });
          
          // Generate markdown documentation
          let markdown = `# Version Functional Release Status
          
          **Generated**: ${new Date().toISOString()}
          
          ## 📊 **Vue d'ensemble**
          
          - **Total versions**: ${docs.summary.total_versions}
          - **Fully functional**: ${docs.summary.fully_functional}
          - **Mostly functional**: ${docs.summary.mostly_functional}
          - **Partially functional**: ${docs.summary.partially_functional}
          - **Non functional**: ${docs.summary.non_functional}
          
          ## 🔍 **Détails par Version**
          
          `;
          
          Object.keys(verificationResults).forEach(versionKey => {
            const result = verificationResults[versionKey];
            const status = result.functionality_score >= 90 ? '✅ Fully Functional' :
                          result.functionality_score >= 70 ? '⚠️ Mostly Functional' :
                          result.functionality_score >= 50 ? '⚠️ Partially Functional' :
                          '❌ Non Functional';
            
            markdown += `
          ### ${result.version} (${result.codename})
          
          - **Status**: ${status}
          - **Functionality Score**: ${result.functionality_score}%
          - **Components Verified**: ${result.components_verified.length}
          - **Components Missing**: ${result.components_missing.length}
          
          #### Components Verified
          ${result.components_verified.map(comp => `- ✅ ${comp}`).join('\n')}
          
          ${result.components_missing.length > 0 ? `
          #### Components Missing
          ${result.components_missing.map(comp => `- ❌ ${comp}`).join('\n')}
          ` : ''}
          
          ---
          `;
          });
          
          markdown += `
          
          ## 🚀 **Recommandations**
          
          ### Versions Fully Functional
          ${Object.keys(verificationResults).filter(key => verificationResults[key].functionality_score >= 90).map(key => `- ${verificationResults[key].version} (${verificationResults[key].codename})`).join('\n')}
          
          ### Versions à Améliorer
          ${Object.keys(verificationResults).filter(key => verificationResults[key].functionality_score < 90).map(key => `- ${verificationResults[key].version} (${verificationResults[key].codename}) - ${verificationResults[key].functionality_score}%`).join('\n')}
          
          ## 📋 **Actions Requises**
          
          ${Object.keys(verificationResults).filter(key => verificationResults[key].components_missing.length > 0).map(key => {
            const result = verificationResults[key];
            return `### ${result.version}
            - [ ] Create missing components: ${result.components_missing.join(', ')}
            - [ ] Test functionality
            - [ ] Update documentation`;
          }).join('\n\n')}
          
          ---
          
          *Documentation générée automatiquement par le Version Functional Release Manager*
          `;
          
          // Save documentation
          fs.writeFileSync('releases/functional-status.md', markdown);
          
          console.log('Release documentation generated');
          
          // Output for GitHub Actions
          console.log(`::set-output name=fully_functional::${docs.summary.fully_functional}`);
          console.log(`::set-output name=mostly_functional::${docs.summary.mostly_functional}`);
          console.log(`::set-output name=partially_functional::${docs.summary.partially_functional}`);
          console.log(`::set-output name=non_functional::${docs.summary.non_functional}`);
          EOF
          
          # Run documentation generator
          node tools/generate-release-docs.js
          
      - name: Update project documentation
        id: update_docs
        run: |
          echo "Updating project documentation..."
          
          # Create documentation updater
          cat > tools/update-project-docs.js << 'EOF'
          const fs = require('fs');
          const path = require('path');
          
          // Load verification results
          const verificationResults = JSON.parse(fs.readFileSync('releases/functional-verification.json', 'utf8'));
          
          // Update README.md with version information
          const readmePath = 'README.md';
          let readme = '';
          
          if (fs.existsSync(readmePath)) {
            readme = fs.readFileSync(readmePath, 'utf8');
          }
          
          // Add version functional release section
          const versionSection = `
          
          ## 🚀 **Versions Fonctionnelles**
          
          ### Version Actuelle (1.3.0) - Forum Analysis
          - **Statut**: ${verificationResults.current ? (verificationResults.current.functionality_score >= 90 ? '✅ Fully Functional' : '⚠️ Needs Improvement') : '❌ Unknown'}
          - **Score de fonctionnalité**: ${verificationResults.current ? verificationResults.current.functionality_score + '%' : 'Unknown'}
          - **Composants vérifiés**: ${verificationResults.current ? verificationResults.current.components_verified.length : 'Unknown'}
          - **Drivers**: 156 total (8 intelligents + 148 existants)
          - **Workflows**: 8 GitHub Actions
          - **Outils**: 9 outils intelligents
          
          ### Version Précédente (1.2.0) - Intelligent Driver System
          - **Statut**: ${verificationResults.previous ? (verificationResults.previous.functionality_score >= 90 ? '✅ Fully Functional' : '⚠️ Needs Improvement') : '❌ Unknown'}
          - **Score de fonctionnalité**: ${verificationResults.previous ? verificationResults.previous.functionality_score + '%' : 'Unknown'}
          - **Composants vérifiés**: ${verificationResults.previous ? verificationResults.previous.components_verified.length : 'Unknown'}
          - **Drivers**: 8 intelligents générés
          - **Workflows**: 7 GitHub Actions
          - **Outils**: 8 outils intelligents
          
          ### Version Legacy (1.1.0) - Basic Integration
          - **Statut**: ${verificationResults.legacy ? (verificationResults.legacy.functionality_score >= 90 ? '✅ Fully Functional' : '⚠️ Needs Improvement') : '❌ Unknown'}
          - **Score de fonctionnalité**: ${verificationResults.legacy ? verificationResults.legacy.functionality_score + '%' : 'Unknown'}
          - **Composants vérifiés**: ${verificationResults.legacy ? verificationResults.legacy.components_verified.length : 'Unknown'}
          - **Drivers**: 148 existants convertis
          - **Workflows**: 6 GitHub Actions
          - **Outils**: 6 outils intelligents
          
          ### Migration entre Versions
          
          #### Migration 1.1.0 → 1.3.0
          \`\`\`bash
          # Sauvegarder les données existantes
          cp -r drivers drivers_backup_1.1.0
          
          # Mettre à jour vers 1.3.0
          git pull origin master
          npm install
          
          # Vérifier la migration
          node tools/version-functional-release.js --migrate 1.1.0 1.3.0
          \`\`\`
          
          #### Migration 1.2.0 → 1.3.0
          \`\`\`bash
          # Sauvegarder les données existantes
          cp -r drivers drivers_backup_1.2.0
          
          # Mettre à jour vers 1.3.0
          git pull origin master
          npm install
          
          # Vérifier la migration
          node tools/version-functional-release.js --migrate 1.2.0 1.3.0
          \`\`\`
          
          `;
          
          // Insert version section
          if (readme.includes('## 🚀 **Versions Fonctionnelles**')) {
            // Replace existing section
            readme = readme.replace(
              /## 🚀 \*\*Versions Fonctionnelles\*\*[\s\S]*?(?=## |$)/,
              versionSection.trim()
            );
          } else {
            // Add new section
            readme += versionSection;
          }
          
          // Save updated README
          fs.writeFileSync(readmePath, readme);
          
          console.log('Project documentation updated');
          EOF
          
          # Run documentation updater
          node tools/update-project-docs.js
          
      - name: Commit version functional release results
        id: commit_results
        run: |
          echo "Committing version functional release results..."
          
          git config --local user.email "dylan.rajasekaram+homey@gmail.com"
          git config --local user.name "dlnraja"
          
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "feat: Version functional release management - $(date '+%Y-%m-%d %H:%M:%S') GMT+2 - Created functional releases for all versions - Verified functional components for each version - Generated comprehensive documentation - Updated project documentation with version information - Implemented version functional release manager - Enhanced version management with verification - Added migration guides between versions - Generated by version functional release manager"
            
            git push origin master
            echo "Version functional release results committed and pushed"
          fi
          
      - name: Update changelog
        id: update_changelog
        run: |
          echo "Updating changelog..."
          
          # Create changelog entry
          cat >> CHANGELOG.md << EOF
          
          ## [1.3.1] - $(date '+%Y-%m-%d %H:%M:%S') GMT+2
          
          ### Added
          - Version functional release management system
          - Automated functional component verification
          - Comprehensive release documentation generation
          - Version comparison and migration guides
          - Functional status tracking for all versions
          
          ### Enhanced
          - Version management with automatic verification
          - Release documentation with detailed status
          - Migration support between all versions
          - Project documentation with version information
          - Functional component tracking and reporting
          
          ### Technical
          - Functional verification for all versions
          - Release status tracking and reporting
          - Automated documentation generation
          - Version comparison and analysis
          - Migration guide generation
          
          EOF
          
          echo "Changelog updated"
          
      - name: Final commit with changelog
        run: |
          echo "Final commit with changelog..."
          
          git add CHANGELOG.md
          
          if git diff --staged --quiet; then
            echo "No changelog changes to commit"
          else
            git commit -m "docs: Update changelog for version functional release management - $(date '+%Y-%m-%d %H:%M:%S') GMT+2 - Added comprehensive changelog entry - Documented version functional release features - Updated version to 1.3.1 - Generated by version functional release manager"
            
            git push origin master
            echo "Changelog committed and pushed"
          fi 