name: Complete CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Validate JSON files
        run: |
          node scripts/deep-json-repair.js
  
  test-drivers:
    runs-on: ubuntu-latest
    needs: validate-json
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run driver tests
        run: node tests/full-validation-suite.js
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: reports/validation-report.json
  
  check-coverage:
    runs-on: ubuntu-latest
    needs: test-drivers
    steps:
      - uses: actions/checkout@v3
      
      - name: Check device coverage
        run: |
          node -e "
          const matrix = require('./matrices/complete-device-matrix.json');
          const coverage = matrix.statistics.coverage_percentage;
          console.log('Device coverage: ' + coverage + '%');
          if (coverage < 3) {
            console.error('Coverage too low!');
            process.exit(1);
          }
          "
  
  build-documentation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate documentation
        run: |
          echo '# Supported Devices' > docs/DEVICES.md
          node -e "
          const matrix = require('./matrices/complete-device-matrix.json');
          const fs = require('fs');
          let doc = '# Supported Tuya Zigbee Devices\n\n';
          doc += 'Total: ' + matrix.statistics.total_models + ' models\n\n';
          for (const [category, devices] of Object.entries(matrix.categories)) {
            doc += '## ' + category.charAt(0).toUpperCase() + category.slice(1) + '\n\n';
            for (const [subcategory, items] of Object.entries(devices)) {
              doc += '### ' + subcategory.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()) + '\n\n';
              for (const device of items) {
                doc += '- **' + device.model + '** - ' + device.name + ' (' + device.status + ')\n';
              }
              doc += '\n';
            }
          }
          fs.writeFileSync('docs/DEVICES.md', doc);
          "
      
      - name: Commit documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff --staged --quiet || git commit -m "docs: update device list [skip ci]"
          git push
