name: Validate Homey App
on: { pull_request: {}, push: { branches: [ main, master ] } }

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci || npm i
          npm install -g homey
      
      - name: Run build tools
        run: |
          node tools/strip-bom.js
          node tools/lint-json.js || true
          node tools/matrix-build.js
          node tools/build-dashboard.js
      
      - name: Validate assets
        run: |
          if [ -f "tools/check-assets.js" ]; then
            node tools/check-assets.js
          else
            echo "check-assets.js not found, skipping asset validation"
      
      - name: Validate app.json schema
        run: |
          if [ -f "schemas/app.schema.json" ]; then
            npx ajv validate -s schemas/app.schema.json -d .homeybuild/app.json --all-errors
          else
            echo "No schema found at schemas/app.schema.json, skipping schema validation"
      
      - name: Run Homey validation
        run: homey app validate -l debug || true
      
      - name: Upload drivers dashboard
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name: drivers-dashboard
          path: docs/data/drivers.json
          if-no-files-found: warn