name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm ci
      
      - name: Validate compose
        run: node tools/validate_compose.mjs
      
      - name: Build device matrix
        run: node tools/build_matrix.mjs
      
      - name: Run Homey validation
        run: npx homey app validate
