# Jekyll Configuration for GitHub Pages
# Author: dlnraja (dylan.rajasekaram@gmail.com)
# Date: 2025-07-26

# Site settings
title: "Tuya ZigBee Integration for Homey"
description: "Complete Tuya ZigBee device integration for Homey with local mode priority"
author: "dlnraja"
email: "dylan.rajasekaram@gmail.com"
url: "https://dlnraja.github.io/com.universaltuyazigbee.device"

# GitHub Pages settings
github:
  repository: "dlnraja/com.universaltuyazigbee.device"
  branch: "master"

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages
  - _posts
  - _layouts
  - _includes
  - assets
  - images

# Theme settings (using GitHub Pages compatible theme)
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Site configuration
lang: en
locale: en_US
timezone: Europe/Paris

# SEO settings
seo:
  title: "Tuya ZigBee Integration for Homey"
  description: "Complete Tuya ZigBee device integration for Homey with local mode priority"
  author: "dlnraja"
  image: "/assets/images/logo.png"
  twitter:
    creator: "@dlnraja"
    site: "@homey"

# Analytics (optional)
google_analytics: ""
google_analytics_anonymize_ip: true

# Social media
social:
  name: "dlnraja"
  links:
    - "https://github.com/dlnraja"
    - "https://community.homey.app"

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Dashboard"
    url: "/dashboard/"
  - title: "Documentation"
    url: "/docs/"
  - title: "Changelog"
    url: "/CHANGELOG/"
  - title: "Installation"
    url: "/INSTALLATION/"
  - title: "Troubleshooting"
    url: "/TROUBLESHOOTING/"

# Footer
footer:
  text: "Developed by dlnraja with ❤️ for the Homey community"
  links:
    - text: "GitHub"
      url: "https://github.com/dlnraja/com.universaltuyazigbee.device"
    - text: "Homey Community"
      url: "https://community.homey.app"
    - text: "Issues"
      url: "https://github.com/dlnraja/com.universaltuyazigbee.device/issues" 

