# auto-enrich-drivers.yml
# Description: Workflow automatisé pour auto enrich drivers
# Date: 2025-07-25
# Version: 1.0

name: Enrichissement Automatique des Drivers


# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cr
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: '0 4 * * *'
  workflow_dispatch:

jobs:
  enrich-drivers:
    runs-
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: ubuntu-latest
    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_VERSION: '18'
        PYTHON_VERSION: '3.11'

    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-versi
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: 18
      - name: Installer les dépendances
        run: npm install || true
      - name: Fusion & enrichissement automatique des drivers
        run: node scripts/merge_enrich_drivers.js
      - name: Commit & Push enrichissement
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add drivers/*/driver.compose.json logs/merge_enrich_drivers.log
          git commit -m "feat(drivers): enrichissement automatique (fusion, manufacturers, logs) [bot]" || echo "Nothing to commit"
          git push
      - name: Générer un log dans le dashboard
        run: |
          echo "$(date -u) : Drivers enrichis automatiquement (voir logs/merge_enrich_drivers.log)" >> dashboard/enrichissement.log
          git add dashboard/enrichissement.log
          git commit -m "docs(dashboard): log enrichissement automatique" || true
          git push 

