
name: Auto Translation Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 */6 $TemplatePath CHANGELOG.md CODE_OF_CONDUCT.md CONTRIBUTING.md Gemfile LICENSE README.md README.md.backup README.txt README_ES.md RELEASE_NOTES_v1.0.0.md STRUCTURE_CONFIG.md VERSIONING.md app.js app.json assets backup bigfiles.txt build-and-run.cmd config data docs drivers lib locales logs olution-strategy package.json quick-start.cmd rapports reports run-project.cmd scripts tatus tsconfig.json update-all-workflows.yml $TemplatePath CHANGELOG.md CODE_OF_CONDUCT.md CONTRIBUTING.md Gemfile LICENSE README.md README.md.backup README.txt README_ES.md RELEASE_NOTES_v1.0.0.md STRUCTURE_CONFIG.md VERSIONING.md app.js app.json assets backup bigfiles.txt build-and-run.cmd config data docs drivers lib locales logs olution-strategy package.json quick-start.cmd rapports reports run-project.cmd scripts tatus tsconfig.json update-all-workflows.yml *  # Every 6 hours

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Auto Translate Content
        run: |
          echo 🌐 Auto translating content...
          bash scripts/linux/automation/auto-translation-push.sh
          
      - name: Build and test
        run: |
          echo 🔧 Building and testing...
          npm run build
          npm test
          
      - name: Commit translated changes
        run: |
          git config --local user.email dylan.rajasekaram@gmail.com
          git config --local user.name dlnraja
          git add .
          git commit -m 🌐 Auto Translation - Sun Jul 27 02:06:45 CEST 2025 - English: Primary, French: Secondary, Spanish: Tertiary
          git push
          
      - name: Create translation report
        run: |
          echo 📊 Creating translation report...
          echo Translation completed successfully > logs/translation-status.txt

