# Description: Réorganisation automatique des fichiers Markdown à chaque push
name: Auto-Markdown-Reorganization
on:
  push:
    branches: [ master ]
    paths:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  reorganize-markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Git
      run: |
        git config --global user.name "dlnraja"
        git config --global user.email "dylan.rajasekaram@gmail.com"
        
    - name: Reorganize Markdown Files
      run: |
        echo "Reorganisation automatique des fichiers Markdown..."
        
        # Créer les dossiers
        mkdir -p docs/todo docs/locales
        
        # Déplacer les fichiers TODO
        for file in TODO_*.md; do
          if [ -f "" ]; then
            mv "" "docs/todo/"
            echo "Deplace:  -> docs/todo/"
          fi
        done
        
        # Déplacer les fichiers de locales
        if [ -d "locales" ]; then
          for file in locales/*.md; do
            if [ -f "" ]; then
              mv "" "docs/locales/"
              echo "Deplace:  -> docs/locales/"
            fi
          done
        fi
        
        # Copier les fichiers principaux
        cp README.md docs/ 2>/dev/null || echo "README.md non trouve"
        cp CHANGELOG.md docs/ 2>/dev/null || echo "CHANGELOG.md non trouve"
        cp CONTRIBUTING.md docs/ 2>/dev/null || echo "CONTRIBUTING.md non trouve"
        
        # Créer l'index
        cat > docs/INDEX.md << 'EOF'
# Documentation Universal TUYA Zigbee Device

## Structure des fichiers Markdown

### Documentation principale
- [README.md](README.md) - Documentation principale du projet
- [CHANGELOG.md](CHANGELOG.md) - Historique des changements
- [CONTRIBUTING.md](CONTRIBUTING.md) - Guide de contribution

### Fichiers TODO
- [TODO_CURSOR_NATIVE.md](todo/TODO_CURSOR_NATIVE.md) - TODO principal
- [TODO_PROJET.md](todo/TODO_PROJET.md) - TODO du projet
- [TODO_CURSOR_COMPLET.md](todo/TODO_CURSOR_COMPLET.md) - TODO complet
- [TODO_CURSOR_INCREMENTAL.md](todo/TODO_CURSOR_INCREMENTAL.md) - TODO incrémental
- [TODO_COMPLETE_FIX.md](todo/TODO_COMPLETE_FIX.md) - TODO des corrections

### Traductions
- [English](locales/en.md) - Documentation en anglais
- [Français](locales/fr.md) - Documentation en français
- [Tamil](locales/ta.md) - Documentation en tamoul
- [Dutch](locales/nl.md) - Documentation en néerlandais

## Métriques du projet
- **Drivers Tuya Zigbee** : 215 drivers
- **Workflows GitHub Actions** : 57 workflows
- **Langues supportées** : 4 (EN/FR/TA/NL)
- **Mode YOLO** : Activé avec auto-approve et auto-continue

## Focus exclusif Tuya Zigbee
Ce projet se concentre exclusivement sur l'écosystème Tuya Zigbee pour Homey, avec support complet des 215 drivers et automatisation avancée.

*Dernière mise à jour : 07/25/2025 15:33:43*
EOF
        
    - name: Commit and Push
      run: |
        git add .
        git commit -m "[YOLO] Reorganisation automatique des fichiers Markdown - Structure optimisee avec docs/, docs/todo/, docs/locales/. Focus exclusif Tuya Zigbee maintenu."
        git push origin master
        
    - name: Success
      run: |
        echo "Reorganisation automatique des fichiers Markdown terminee!"
        echo "Structure creee:"
        echo "- docs/ - Documentation principale"
        echo "- docs/todo/ - Fichiers TODO"
        echo "- docs/locales/ - Traductions"
        echo "- docs/INDEX.md - Index des fichiers"
        
    - name: Clean up package-lock.json
      if: always()
      run: |
        echo "Suppression du package-lock.json pour éviter la surcharge du repo."
        rm -f package-lock.json
