# auto-merge.yml
# Description: Workflow automatisé pour auto merge
# Date: 2025-07-25
# Version: 1.0

name: Auto-merge PR

# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on:
  pull_request:
    types:
      - labeled
jobs:
  automerge:
    runs-
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_VERSION: '18'
        PYTHON_VERSION: '3.11'

    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

