name: Ultimate Zigbee Hub Auto Publish v2.0.8

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Homey CLI
      run: |
        npm install -g @athombv/homey-cli
        npm install fs-extra homey-zigbeedriver zigbee-clusters
        
    - name: Login to Homey
      env:
        HOMEY_TOKEN: ${{ secrets.HOMEY_TOKEN }}
      run: echo "$HOMEY_TOKEN" | homey login
      
    - name: Buffer-Safe Publication with Expect
      run: |
        sudo apt-get install -y expect
        expect << 'EOF'
        set timeout 300
        spawn homey app publish
        expect {
          "uncommitted changes" { send "y\r"; exp_continue }
          "update.*version" { send "y\r"; exp_continue }
          "What kind of update" { send "patch\r"; exp_continue }
          "changelog" { send "v2.0.8 - Buffer optimization + comprehensive unbranded driver enhancement with 101+ professional drivers following Johan Benz standards\r"; exp_continue }
          "Are you sure" { send "y\r"; exp_continue }
          "published" { exit 0 }
          eof { exit 0 }
          timeout { exit 1 }
        }
        EOF
