# 🚀 Auto-Tutorial Generator - Tuya Zigbee Project
# Génération automatique de tutoriels pour les drivers

name: 📚 Auto-Tutorial Generator

on:
  push:
    paths:
      - 'drivers/**'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Tous les jours à 3h00 UTC

jobs:
  generate-tutorials:
    runs-on: ubuntu-latest
    name: 📚 Génération automatique de tutoriels
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: 📦 Install dependencies
        run: |
          npm install
          npm install -g markdown-it
          
      - name: 🔍 Generate tutorials
        run: |
          echo "Generating tutorials for drivers..."
          mkdir -p docs/tutorials
          
          # Créer un script simple pour générer les tutoriels
          cat > generate_tutorials.js << 'EOF'
          const fs = require('fs');
          const path = require('path');
          
          const drivers = ['curtain_module', 'rain_sensor', 'multi_sensor', 'smart_plug', 'remote_control'];
          
          drivers.forEach(driver => {
            const tutorialContent = `# 📚 Tutoriel - ${driver}
          
          ## 🎯 Vue d'ensemble
          Ce tutoriel vous guide dans l'installation et la configuration du driver **${driver}** pour Homey.
          
          ## 📋 Prérequis
          - Homey avec firmware 8.0+
          - Application Tuya Zigbee installée
          - Appareil compatible ${driver}
          
          ## 🔧 Installation
          
          ### Étape 1: Ajout du driver
          1. Ouvrez l'application Tuya Zigbee sur Homey
          2. Allez dans l'onglet "Drivers"
          3. Recherchez "${driver}"
          4. Cliquez sur "Installer"
          
          ### Étape 2: Configuration
          1. Appuyez sur le bouton "+" pour ajouter un appareil
          2. Sélectionnez "${driver}" dans la liste
          3. Suivez les instructions à l'écran
          
          ## ⚙️ Configuration avancée
          
          ### Paramètres recommandés
          - **Polling interval**: 60 secondes
          - **Battery threshold**: 20%
          - **Auto-reconnect**: Activé
          
          ### Dépannage
          - **Problème**: L'appareil ne se connecte pas
            - **Solution**: Vérifiez que l'appareil est en mode pairing
          - **Problème**: Batterie faible
            - **Solution**: Remplacez les piles et recalibrez
          
          ## 📊 Monitoring
          - Surveillez la batterie dans l'application
          - Vérifiez les logs pour les erreurs
          - Utilisez le dashboard pour les statistiques
          
          ## 🔗 Liens utiles
          - [Documentation officielle](../README.md)
          - [Support communautaire](https://github.com/dlnraja/com.tuya.zigbee/issues)
          - [Dashboard temps réel](../dashboard/)
          
          ---
          *Généré automatiquement le ${new Date().toISOString()}*
          `;
          
            fs.writeFileSync(`docs/tutorials/${driver}_tutorial.md`, tutorialContent);
            console.log(`Generated tutorial for ${driver}`);
          });
          
          // Générer le guide d'installation
          const installationGuide = `# 🚀 Guide d'Installation - Tuya Zigbee
          
          ## 📋 Prérequis système
          - Homey avec firmware 8.0+
          - Connexion internet stable
          - Compte Tuya (optionnel)
          
          ## 🔧 Installation étape par étape
          
          ### 1. Installation de l'application
          1. Ouvrez l'App Store sur Homey
          2. Recherchez "Tuya Zigbee"
          3. Cliquez sur "Installer"
          4. Attendez la fin de l'installation
          
          ### 2. Configuration initiale
          1. Ouvrez l'application Tuya Zigbee
          2. Acceptez les conditions d'utilisation
          3. Configurez votre région
          4. Testez la connexion
          
          ### 3. Ajout d'appareils
          1. Appuyez sur "+" pour ajouter un appareil
          2. Sélectionnez le type d'appareil
          3. Suivez les instructions de pairing
          4. Configurez les paramètres
          
          ## ⚙️ Configuration avancée
          
          ### Paramètres réseau
          - **Zigbee Channel**: Auto-détection
          - **Security**: WPA2 recommandé
          - **Range**: Jusqu'à 100m en extérieur
          
          ### Optimisation des performances
          - Placez le Homey au centre de votre installation
          - Évitez les interférences WiFi
          - Utilisez des répéteurs si nécessaire
          
          ## 🔍 Dépannage
          
          ### Problèmes courants
          1. **Appareil non détecté**
             - Vérifiez le mode pairing
             - Redémarrez l'appareil
             - Vérifiez la distance
          
          2. **Connexion instable**
             - Vérifiez la batterie
             - Déplacez l'appareil plus près
             - Ajoutez un répéteur
          
          3. **Erreurs de mise à jour**
             - Vérifiez la connexion internet
             - Redémarrez Homey
             - Contactez le support
          
          ## 📞 Support
          - **Documentation**: [README.md](../README.md)
          - **Issues**: [GitHub](https://github.com/dlnraja/com.tuya.zigbee/issues)
          - **Dashboard**: [Temps réel](../dashboard/)
          
          ---
          *Généré automatiquement le ${new Date().toISOString()}*
          `;
          
          fs.writeFileSync('docs/INSTALLATION_GUIDE.md', installationGuide);
          console.log('Generated installation guide');
          
          // Générer le guide de dépannage
          const troubleshootingGuide = `# 🔧 Guide de Dépannage - Tuya Zigbee
          
          ## 🚨 Problèmes courants et solutions
          
          ### 1. Appareil non détecté
          **Symptômes**: L'appareil n'apparaît pas dans la liste
          **Solutions**:
          - Vérifiez que l'appareil est en mode pairing
          - Redémarrez l'appareil
          - Vérifiez la distance (max 10m)
          - Changez les piles si nécessaire
          
          ### 2. Connexion instable
          **Symptômes**: L'appareil se déconnecte régulièrement
          **Solutions**:
          - Déplacez l'appareil plus près du Homey
          - Ajoutez un répéteur Zigbee
          - Vérifiez les interférences WiFi
          - Mettez à jour le firmware
          
          ### 3. Batterie faible
          **Symptômes**: Alertes de batterie fréquentes
          **Solutions**:
          - Remplacez les piles
          - Vérifiez la qualité des piles
          - Réduisez la fréquence de polling
          - Recalibrez le capteur
          
          ### 4. Erreurs de mise à jour
          **Symptômes**: Échec des mises à jour
          **Solutions**:
          - Vérifiez la connexion internet
          - Redémarrez Homey
          - Vérifiez l'espace disque
          - Contactez le support
          
          ## 📊 Diagnostic
          
          ### Logs utiles
          - **Application logs**: Settings > System > Logs
          - **Driver logs**: Dans l'application Tuya Zigbee
          - **Network logs**: Pour les problèmes de connexion
          
          ### Outils de diagnostic
          - **Dashboard**: Monitoring temps réel
          - **Terminal**: Scripts PowerShell de diagnostic
          - **API**: Endpoints de diagnostic
          
          ## 🆘 Support avancé
          
          ### Informations à fournir
          1. Version de Homey
          2. Version de l'application
          3. Type d'appareil
          4. Logs d'erreur
          5. Étapes de reproduction
          
          ### Contacts
          - **GitHub Issues**: [Lien](https://github.com/dlnraja/com.tuya.zigbee/issues)
          - **Documentation**: [README.md](../README.md)
          - **Dashboard**: [Monitoring](../dashboard/)
          
          ---
          *Généré automatiquement le ${new Date().toISOString()}*
          `;
          
          fs.writeFileSync('docs/TROUBLESHOOTING.md', troubleshootingGuide);
          console.log('Generated troubleshooting guide');
          EOF
          
          node generate_tutorials.js
          
      - name: 📝 Commit tutorials
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "📚 [$(date -u '+%Y-%m-%d %H:%M UTC')] Auto-tutorials: Guides générés pour 5 drivers + guides installation/dépannage. Powered by GitHub Actions"
          git push
          
      - name: 📈 Update tutorial stats
        run: |
          echo "Tutorials generated successfully!"
          echo "Files created:"
          echo "- 5 driver tutorials"
          echo "- Installation guide"
          echo "- Troubleshooting guide"
          echo "Next update: Tomorrow 3:00 UTC" 