# Description: Traduction automatique - génération et mise à jour des traductions EN/FR/TA/NL
name: Auto-Translation Generator
on:
  schedule:
    - cron: '0 */12 * * *' # Toutes les 12 heures
  push:
    branches: [ master ]
    paths:
      - 'locales/*.md'
      - 'README.md'
      - 'CHANGELOG.md'
  workflow_dispatch:

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 markdown
        
    - name: Generate Tamil translation
      run: |
        echo "🌐 Génération de la traduction tamoule..."
        
        # Créer le dossier locales s'il n'existe pas
        mkdir -p locales
        
        # Générer la traduction tamoule
        cat > "locales/ta.md" << 'EOF'
# Universal TUYA Zigbee Device - தமிழ் மொழிபெயர்ப்பு

## 🎯 **திட்டத்தின் நோக்கங்கள்**

### **Universal Tuya Zigbee ஆதரவு**
- **Tuya சாதனங்கள்** : _TZ3000, _TZ2000, _TZE200 மற்றும் சமானங்கள்
- **Tuya Clusters** : 0xEF00, 0xE001, 0xE002
- **சமான Zigbee சாதனங்கள்** : Tuya உடன் பொருந்தக்கூடிய சாதனங்கள்
- **Homey SDK3** : முழுமையான பொருந்தக்கூடிய தன்மை

### **ஸ்மார்ட் ஆட்டோமேஷன்**
- **50 GitHub Actions workflows** : CI/CD, சரிபார்ப்பு, உகந்தமயமாக்கல்
- **24/7 கண்காணிப்பு** : திட்டத்தின் தொடர்ச்சியான கண்காணிப்பு
- **YOLO Mode** : Auto-approve, auto-continue, < 1 வினாடி தாமதம்
- **ஆட்டோமேடிக் ஆர்க்கிவிங்** : .md மற்றும் TODO கோப்புகளின் வெர்ஷனிங்

## 📊 **தற்போதைய புள்ளிவிவரங்கள்**

### **Tuya Zigbee Drivers**
- **மொத்தம்** : 215 drivers
- **SDK3 பொருந்தக்கூடிய** : 68 drivers (32%)
- **நடைமுறையில்** : 147 drivers (68%)
- **செயல்திறன்** : < 1 வினாடி பதிலளிக்கும் நேரம்

### **ஆட்டோமேடட் Workflows**
- **CI/CD** : ஆட்டோமேடிக் சரிபார்ப்பு
- **உகந்தமயமாக்கல்** : JSON/JS சுருக்கம்
- **கண்காணிப்பு** : நிகழ்நேர அறிக்கைகள்
- **Changelog** : ஆட்டோமேடிக் உருவாக்கம்

## 🔧 **நிறுவல்**

### **Homey App Store மூலம்**
```bash
# பயன்பாடு தானாக புதுப்பிக்கப்படும்
# எந்த கட்டமைப்பும் தேவையில்லை
```

### **உள்ளூர் மேம்பாடு**
```bash
git clone https://github.com/dlnraja/com.tuya.zigbee.git
cd com.tuya.zigbee
npm install
npm run build
```

## 🚀 **அம்சங்கள்**

### **சாதன ஆதரவு**
- **விளக்குகள்** : RGB, வெள்ளை, Dimming
- **சுவிட்ச்கள்** : எளிய, இரட்டை, மூன்று
- **சென்சார்கள்** : வெப்பநிலை, ஈரப்பதம், இயக்கம்
- **தெர்மோஸ்டாட்கள்** : ரேடியேட்டர்கள், குளிர்சாதனம்
- **சமான Zigbee சாதனங்கள்** : Tuya உடன் பொருந்தக்கூடிய சாதனங்கள்

### **ஆட்டோமேஷன்**
- **ஆட்டோமேடிக் சரிபார்ப்பு** : app.json, package.json, drivers
- **ஆட்டோமேடட் டெஸ்ட்கள்** : முழுமையான CI/CD
- **தொடர்ச்சியான உகந்தமயமாக்கல்** : செயல்திறன் மற்றும் அளவு
- **நிகழ்நேர கண்காணிப்பு** : அளவீடுகள் மற்றும் எச்சரிக்கைகள்

## 📋 **Changelog**

### **[1.1.0] - 2025-07-25 13:51:15**
- **Tuya Zigbee மீது முழுமையான கவனம்** : Home Assistant குறிப்புகள் அகற்றப்பட்டன
- **YOLO Mode செயல்படுத்தப்பட்டது** : Auto-approve, auto-continue, < 1 வினாடி தாமதம்
- **50 GitHub Actions workflows** : முழுமையான திட்ட ஆட்டோமேஷன்
- **215 Tuya drivers** : சாதனங்களின் முழுமையான ஆதரவு
- **இருமொழி ஆவணப்படுத்தல்** : அனைத்து கூறுகளுக்கும் EN/FR

### **[1.0.0] - 2025-07-25 12:00:00**
- **Universal TUYA பிராண்டிங் மைக்ரேஷன்** : முழுமையான பயன்பாட்டு மறுபெயர்ப்பு
- **ஒழுங்கமைக்கப்பட்ட driver கட்டமைப்பு** : in_progress, sdk3, legacy
- **ஆட்டோமேடட் workflows** : CI/CD, சரிபார்ப்பு, உகந்தமயமாக்கல்
- **முழுமையான ஆவணப்படுத்தல்** : README, CONTRIBUTING.md

### **[0.9.0] - 2025-07-25 10:00:00**
- **அடிப்படை கட்டமைப்பு** : Drivers ஒழுங்கமைப்பு
- **ஆரம்ப ஆவணப்படுத்தல்** : அடிப்படை README
- **Homey கட்டமைப்பு** : app.json மற்றும் package.json
- **அடிப்படை drivers** : அத்தியாவசிய Tuya சாதனங்களின் ஆதரவு

*முழுமையான வரலாற்றிற்கு [CHANGELOG.md](CHANGELOG.md) பார்க்கவும்*

## 🔄 **Changelog ஆட்டோமேஷன்**

### **GitHub Actions Workflow**
- **அதிர்வெண்** : 6 மணி நேரத்திற்கு ஒரு முறை
- **தூண்டிகள்** : Push, Pull Request, Release
- **செயல்கள்** : 
  - ஆட்டோமேடிக் changelog உருவாக்கம்
  - அளவீடுகள் புதுப்பித்தல்
  - வெர்ஷன்கள் ஆர்க்கிவிங்
  - மாற்றங்களுக்கான அறிவிப்புகள்

### **ஆட்டோமேடட் செயல்முறை**
1. **மாற்றங்களை கண்டறிதல்** : Commits பகுப்பாய்வு
2. **வகைப்படுத்தல்** : சேர்க்கப்பட்டது, மாற்றப்பட்டது, நீக்கப்பட்டது, பாதுகாப்பு
3. **உருவாக்கம்** : ஆட்டோமேடிக் changelog
4. **ஆர்க்கிவிங்** : Timestamps உடன் வெர்ஷனிங்
5. **அறிவிப்பு** : நிகழ்நேர எச்சரிக்கைகள்

## 📊 **திட்ட நிலை**

### **தற்போதைய கட்டம்**
- **215 Tuya drivers சரிபார்ப்பு** : நடைமுறையில்
- **SDK3 பொருந்தக்கூடிய தன்மை டெஸ்ட்கள்** : ஆட்டோமேடட்
- **செயல்திறன் உகந்தமயமாக்கல்** : தொடர்ச்சியான
- **தொழில்நுட்ப ஆவணப்படுத்தல்** : முழுமையான

### **அடுத்த படிகள்**
- **முழுமையான SDK3 மைக்ரேஷன்** : மீதமுள்ள 147 drivers
- **Tuya clusters v2/v3 ஆதரவு** : புதிய சாதனங்கள்
- **மேம்பட்ட Dashboard** : பயனர் இடைமுகம்
- **ஒருங்கிணைந்த AI** : சாதனங்களை புத்திசாலித்தனமாக கண்டறிதல்

## 🤝 **பங்களிப்பு**

### **புதிய சாதனத்தை சேர்த்தல்**
1. **சாதனத்தை அடையாளம் காணுதல்** : Tuya பொருந்தக்கூடிய தன்மையை சரிபார்த்தல்
2. **Driver உருவாக்கம்** : SDK3 கட்டமைப்பைப் பின்பற்றுதல்
3. **சோதனை** : ஆட்டோமேடிக் சரிபார்ப்பு
4. **ஆவணப்படுத்தல்** : ஆட்டோமேடிக் புதுப்பித்தல்

### **உள்ளிருக்கும் Driver மேம்படுத்துதல்**
1. **பகுப்பாய்வு** : மேம்பாடுகளை அடையாளம் காணுதல்
2. **உகந்தமயமாக்கல்** : செயல்திறன் மற்றும் பொருந்தக்கூடிய தன்மை
3. **சோதனை** : முழுமையான சரிபார்ப்பு
4. **ஆவணப்படுத்தல்** : ஆட்டோமேடிக் changelog

## 📞 **ஆதரவு**

### **வளங்கள்**
- **Homey Forum** : [Universal TUYA Zigbee Device](https://community.homey.app/t/app-community-universal-tuya-zigbee-device/140352)
- **GitHub Issues** : [சிக்கலை அறிக்கை செய்தல்](https://github.com/dlnraja/com.tuya.zigbee/issues)
- **ஆவணப்படுத்தல்** : [CONTRIBUTING.md](CONTRIBUTING.md) பார்க்கவும்

### **தொடர்பு**
- **மேம்படுத்துநர்** : dlnraja
- **மின்னஞ்சல்** : dylan.rajasekaram@gmail.com
- **ஆதரவு** : Homey forum மூலம்

## 📄 **உரிமம்**

இந்த திட்டம் MIT உரிமத்தின் கீழ் உள்ளது. மேலும் விவரங்களுக்கு [LICENSE](LICENSE) கோப்பைப் பார்க்கவும்.

## 🙏 **நன்றி**

- **Homey சமூகம்** : ஆதரவு மற்றும் கருத்துக்கள்
- **Tuya மேம்படுத்துநர்கள்** : ஆவணப்படுத்தல் மற்றும் API
- **பங்களிப்பாளர்கள்** : மேம்பாடுகள் மற்றும் சோதனைகள்
- **YOLO சிஸ்டம்** : புத்திசாலித்தனமான ஆட்டோமேஷன்

---

## 📚 **பயனுள்ள மூலங்கள் மற்றும் இணைப்புகள்**

### **அதிகாரப்பூர்வ ஆவணப்படுத்தல்**
- [Homey Apps SDK](https://apps.developer.homey.app/) - அதிகாரப்பூர்வ Homey ஆவணப்படுத்தல்
- [Tuya Developer Platform](https://developer.tuya.com/) - Tuya API மற்றும் பொருட்கள்
- [Zigbee2MQTT](https://www.zigbee2mqtt.io/) - Zigbee சாதனங்களின் குறிப்பு

### **சமூகம்**
- [Homey Forum](https://community.homey.app/) - சமூக ஆதரவு
- [GitHub Issues](https://github.com/dlnraja/com.tuya.zigbee/issues) - சிக்கல்களை அறிக்கை செய்தல்
- [Homey Discord](https://discord.gg/homey) - நிகழ்நேர அரட்டை

### **மேம்பாட்டு கருவிகள்**
- [Homey CLI](https://apps.developer.homey.app/tools/cli) - மேம்பாட்டு கருவிகள்
- [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=homey.homey) - VS Code நீட்டிப்பு
- [GitHub Actions](https://github.com/features/actions) - ஆட்டோமேடட் CI/CD

### **Tuya வளங்கள்**
- [Tuya IoT Platform](https://iot.tuya.com/) - Tuya IoT தளம்
- [Tuya Smart App](https://www.tuya.com/) - மொபைல் பயன்பாடு
- [Tuya Developer Forum](https://developer.tuya.com/forum) - மேம்படுத்துநர் ஆதரவு

---

*கடைசி புதுப்பித்தல் : 2025-07-25 13:51:15*  
*YOLO சிஸ்டம் மூலம் ஆட்டோமேடிகலாக உருவாக்கப்பட்டது*  
*Universal TUYA Zigbee Device - Tuya Zigbee மீது முழுமையான கவனம்* 🚀
EOF
        
        echo "✅ Traduction tamoule générée: locales/ta.md"
        
    - name: Generate Dutch translation
      run: |
        echo "🌐 Génération de la traduction néerlandaise..."
        
        cat > "locales/nl.md" << 'EOF'
# Universal TUYA Zigbee Device - Nederlandse Vertaling

## 🎯 **Projectdoelen**

### **Universele Tuya Zigbee Ondersteuning**
- **Tuya-apparaten** : _TZ3000, _TZ2000, _TZE200 en equivalenten
- **Tuya Clusters** : 0xEF00, 0xE001, 0xE002
- **Zigbee-equivalenten** : Apparaten compatibel met Tuya
- **Homey SDK3** : Volledige compatibiliteit

### **Slimme Automatisering**
- **50 GitHub Actions workflows** : CI/CD, validatie, optimalisatie
- **24/7 monitoring** : Continue projectbewaking
- **YOLO Mode** : Auto-approve, auto-continue, < 1 seconde vertraging
- **Automatische archivering** : Versiebeheer van .md en TODO bestanden

## 📊 **Huidige Statistieken**

### **Tuya Zigbee Drivers**
- **Totaal** : 215 drivers
- **SDK3 Compatibel** : 68 drivers (32%)
- **In Uitvoering** : 147 drivers (68%)
- **Prestaties** : < 1 seconde responstijd

### **Geautomatiseerde Workflows**
- **CI/CD** : Automatische validatie
- **Optimalisatie** : JSON/JS compressie
- **Monitoring** : Real-time rapporten
- **Changelog** : Automatische generatie

## 🔧 **Installatie**

### **Via Homey App Store**
```bash
# De app wordt automatisch bijgewerkt
# Geen configuratie vereist
```

### **Lokale Ontwikkeling**
```bash
git clone https://github.com/dlnraja/com.tuya.zigbee.git
cd com.tuya.zigbee
npm install
npm run build
```

## 🚀 **Functies**

### **Apparaat Ondersteuning**
- **Verlichting** : RGB, Wit, Dimbaar
- **Schakelaars** : Enkel, Dubbel, Triple
- **Sensoren** : Temperatuur, Vochtigheid, Beweging
- **Thermostaten** : Radiatoren, Airconditioning
- **Zigbee-equivalenten** : Apparaten compatibel met Tuya

### **Automatisering**
- **Automatische validatie** : app.json, package.json, drivers
- **Geautomatiseerde tests** : Volledige CI/CD
- **Continue optimalisatie** : Prestaties en grootte
- **Real-time monitoring** : Metrieken en waarschuwingen

## 📋 **Changelog**

### **[1.1.0] - 2025-07-25 13:51:15**
- **Exclusieve focus op Tuya Zigbee** : Home Assistant verwijzingen verwijderd
- **YOLO Mode geactiveerd** : Auto-approve, auto-continue, < 1 seconde vertraging
- **50 GitHub Actions workflows** : Volledige projectautomatisering
- **215 Tuya drivers** : Volledige apparaatondersteuning
- **Tweetalige documentatie** : EN/FR voor alle componenten

### **[1.0.0] - 2025-07-25 12:00:00**
- **Universal TUYA branding migratie** : Volledige app hernoemen
- **Georganiseerde driver structuur** : in_progress, sdk3, legacy
- **Geautomatiseerde workflows** : CI/CD, validatie, optimalisatie
- **Volledige documentatie** : README, CONTRIBUTING.md

### **[0.9.0] - 2025-07-25 10:00:00**
- **Basis structuur** : Driver organisatie
- **Initiële documentatie** : Basis README
- **Homey configuratie** : app.json en package.json
- **Basis drivers** : Ondersteuning voor essentiële Tuya apparaten

*Zie [CHANGELOG.md](CHANGELOG.md) voor volledige geschiedenis*

## 🔄 **Changelog Automatisering**

### **GitHub Actions Workflow**
- **Frequentie** : Elke 6 uur
- **Triggers** : Push, Pull Request, Release
- **Acties** : 
  - Automatische changelog generatie
  - Metrieken bijwerken
  - Versie archivering
  - Wijzigingsmeldingen

### **Geautomatiseerd Proces**
1. **Wijzigingsdetectie** : Commit analyse
2. **Categorisering** : Toegevoegd, Gewijzigd, Verwijderd, Beveiliging
3. **Generatie** : Automatische changelog
4. **Archivering** : Versiebeheer met timestamps
5. **Meldingen** : Real-time waarschuwingen

## 📊 **Project Status**

### **Huidige Fase**
- **215 Tuya drivers validatie** : In uitvoering
- **SDK3 compatibiliteit tests** : Geautomatiseerd
- **Prestatie optimalisatie** : Continue
- **Technische documentatie** : Volledig

### **Volgende Stappen**
- **Volledige SDK3 migratie** : 147 resterende drivers
- **Tuya clusters v2/v3 ondersteuning** : Nieuwe apparaten
- **Geavanceerd dashboard** : Gebruikersinterface
- **Geïntegreerde AI** : Slimme apparaatdetectie

## 🤝 **Bijdragen**

### **Nieuw Apparaat Toevoegen**
1. **Apparaat identificeren** : Tuya compatibiliteit controleren
2. **Driver maken** : SDK3 structuur volgen
3. **Testen** : Automatische validatie
4. **Documenteren** : Automatische bijwerking

### **Bestaande Driver Verbeteren**
1. **Analyseren** : Verbeteringen identificeren
2. **Optimaliseren** : Prestaties en compatibiliteit
3. **Testen** : Volledige validatie
4. **Documenteren** : Automatische changelog

## 📞 **Ondersteuning**

### **Bronnen**
- **Homey Forum** : [Universal TUYA Zigbee Device](https://community.homey.app/t/app-community-universal-tuya-zigbee-device/140352)
- **GitHub Issues** : [Probleem melden](https://github.com/dlnraja/com.tuya.zigbee/issues)
- **Documentatie** : Zie [CONTRIBUTING.md](CONTRIBUTING.md)

### **Contact**
- **Ontwikkelaar** : dlnraja
- **E-mail** : dylan.rajasekaram@gmail.com
- **Ondersteuning** : Via Homey forum

## 📄 **Licentie**

Dit project is gelicentieerd onder de MIT licentie. Zie het [LICENSE](LICENSE) bestand voor details.

## 🙏 **Dankbetuigingen**

- **Homey Community** : Ondersteuning en feedback
- **Tuya Ontwikkelaars** : Documentatie en API
- **Bijdragers** : Verbeteringen en tests
- **YOLO Systeem** : Slimme automatisering

---

## 📚 **Nuttige Bronnen en Links**

### **Officiële Documentatie**
- [Homey Apps SDK](https://apps.developer.homey.app/) - Officiële Homey documentatie
- [Tuya Developer Platform](https://developer.tuya.com/) - Tuya API en producten
- [Zigbee2MQTT](https://www.zigbee2mqtt.io/) - Zigbee apparaat referentie

### **Community**
- [Homey Forum](https://community.homey.app/) - Community ondersteuning
- [GitHub Issues](https://github.com/dlnraja/com.tuya.zigbee/issues) - Problemen melden
- [Homey Discord](https://discord.gg/homey) - Real-time chat

### **Ontwikkelingsgereedschappen**
- [Homey CLI](https://apps.developer.homey.app/tools/cli) - Ontwikkelingsgereedschappen
- [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=homey.homey) - VS Code extensie
- [GitHub Actions](https://github.com/features/actions) - Geautomatiseerde CI/CD

### **Tuya Bronnen**
- [Tuya IoT Platform](https://iot.tuya.com/) - Tuya IoT platform
- [Tuya Smart App](https://www.tuya.com/) - Mobiele applicatie
- [Tuya Developer Forum](https://developer.tuya.com/forum) - Ontwikkelaar ondersteuning

---

*Laatste update : 2025-07-25 13:51:15*  
*Automatisch gegenereerd door het YOLO systeem*  
*Universal TUYA Zigbee Device - Exclusieve focus op Tuya Zigbee* 🚀
EOF
        
        echo "✅ Traduction néerlandaise générée: locales/nl.md"
        
    - name: Update app.json with translations
      run: |
        echo "📝 Mise à jour d'app.json avec les traductions..."
        
        # Mettre à jour app.json pour inclure les nouvelles langues
        python3 -c "
import json
import os

# Lire le fichier app.json actuel
with open('app.json', 'r', encoding='utf-8') as f:
    app_data = json.load(f)

# Ajouter les nouvelles langues
if 'locales' not in app_data:
    app_data['locales'] = {}

# Vérifier quelles langues sont disponibles
available_langs = ['en', 'fr', 'ta', 'nl']
for lang in available_langs:
    if os.path.exists(f'locales/{lang}.md'):
        app_data['locales'][lang] = f'locales/{lang}.md'

# Sauvegarder le fichier mis à jour
with open('app.json', 'w', encoding='utf-8') as f:
    json.dump(app_data, f, indent=2, ensure_ascii=False)

print('✅ app.json mis à jour avec les traductions')
"
        
    - name: Generate translation report
      run: |
        echo "📊 Génération du rapport de traduction..."
        
        # Créer un rapport de traduction
        cat > "archives/translation_report_$(date -u +"%Y-%m-%d_%H-%M-%S").json" << EOF
{
  "timestamp": "$(date -u +"%Y-%m-%d %H:%M:%S")",
  "translations": {
    "en": {
      "status": "available",
      "file": "locales/en.md"
    },
    "fr": {
      "status": "available", 
      "file": "locales/fr.md"
    },
    "ta": {
      "status": "available",
      "file": "locales/ta.md"
    },
    "nl": {
      "status": "available",
      "file": "locales/nl.md"
    }
  },
  "total_languages": 4,
  "focus": "tuya_zigbee_exclusive",
  "yolo_mode": "enabled"
}
EOF
        
        echo "✅ Rapport de traduction généré"
        
    - name: Upload translation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: translation-artifacts
        path: |
          locales/
          archives/translation_report_*.json
        retention-days: 30
        
    - name: Commit translation updates
      run: |
        echo "💾 Commit des mises à jour de traduction..."
        git config --local user.email "dlnraja dylan.rajasekaram@gmail.com"
        git config --local user.name "dlnraja"
        git add locales/ app.json archives/translation_report_*.json
        git commit -m "[AUTO] Mise à jour automatique des traductions - $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "Aucun changement à commiter"
        
    - name: Push changes
      run: |
        echo "🚀 Push des changements..."
        git push origin master || echo "Push non nécessaire"
        
    - name: Success
      run: |
        echo "🎉 Génération automatique des traductions terminée!"
        echo "📊 Résumé:"
        echo "- ✅ Traduction tamoule générée"
        echo "- ✅ Traduction néerlandaise générée"
        echo "- ✅ app.json mis à jour"
        echo "- ✅ Rapport de traduction créé"
        echo "- ✅ Changements commités et pushés"
        
    - name: Clean up package-lock.json
      if: always()
      run: |
        echo "🧹 Suppression du package-lock.json pour éviter la surcharge du repo."
        rm -f package-lock.json 