# Description: Correction automatique des auteurs Git et amélioration des messages
name: Auto-Git-Author-Fix
on:
  schedule:
    - cron: '0 */6 * * *' # Toutes les 6 heures
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  fix-git-authors:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Récupérer tout l'historique
      
    - name: Setup Git
      run: |
        git config --global user.name "dlnraja"
        git config --global user.email "dylan.rajasekaram@gmail.com"
        
    - name: Fix Git Authors
      run: |
        echo "Correction des auteurs Git..."
        
        # Vérifier les commits avec l'ancien email
        OLD_EMAIL="dylan.rajasekaram+myhomeyapp@gmail.com"
        CORRECT_EMAIL="dylan.rajasekaram@gmail.com"
        CORRECT_AUTHOR="dlnraja"
        
        # Réécrire l'historique si nécessaire
        if git log --author="$OLD_EMAIL" --oneline | head -1; then
          echo "Commits avec l'ancien email trouvés, réécriture en cours..."
          git filter-branch --env-filter "
            if [ \"\$GIT_AUTHOR_EMAIL\" = \"$OLD_EMAIL\" ]
            then
                export GIT_AUTHOR_EMAIL=\"$CORRECT_EMAIL\"
                export GIT_AUTHOR_NAME=\"$CORRECT_AUTHOR\"
            fi
            if [ \"\$GIT_COMMITTER_EMAIL\" = \"$OLD_EMAIL\" ]
            then
                export GIT_COMMITTER_EMAIL=\"$CORRECT_EMAIL\"
                export GIT_COMMITTER_NAME=\"$CORRECT_AUTHOR\"
            fi
          " --tag-name-filter cat -- --branches --tags
        else
          echo "Aucun commit avec l'ancien email trouvé"
        fi
        
    - name: Force Push
      run: |
        echo "Force push des changements..."
        git push origin master --force
        
    - name: Success
      run: |
        echo "Correction des auteurs Git terminée!"
        echo "Résumé:"
        echo "- Auteurs Git corrigés"
        echo "- Historique réécrit"
        echo "- Force push effectué"
        
    - name: Clean up package-lock.json
      if: always()
      run: |
        echo "Suppression du package-lock.json pour éviter la surcharge du repo."
        rm -f package-lock.json
