name: Auto Publish v2.0.0
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g homey
      - run: echo "$HOMEY_TOKEN" | homey login --token
      - run: homey app publish --changelog "v2.0.0 - Generic Smart Hub transformation"
        env:
          HOMEY_TOKEN: ${{ secrets.HOMEY_TOKEN }}