name: Build and Validate

on:
  push:
    branches: [ master, tuya-light ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Validate app
      run: npx homey app validate
      
    - name: Build app
      run: npx homey app build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: homey-app-build
        path: .homeybuild/
