name: Ultimate CI/CD Pipeline
on:
  push:
    branches:
      - main
      - develop
  "pull_request":
    branches:
      - main
  schedule:
    - cron: 0 2 * * *

env:
  "NODE_VERSION": 18
  "HOMEY_CLI_VERSION": latest
jobs:
  setup:
    "runs-on": ubuntu-latest
    outputs:
      "cache_key": "${{ steps.cache.outputs.cache-hit }}"
      "node_version": "${{ env.NODE_VERSION }}"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          "node-version": "${{ env.NODE_VERSION }}"
          cache: npm

      - id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: "${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}"

      - run: npm ci

  "lint_and_test":
    needs: setup
    "runs-on": ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          "node-version": "${{ env.NODE_VERSION }}"
          cache: npm

      - run: npm ci

      - run: npm run lint

      - run: npm test

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()

  "homey_validation":
    needs: setup
    "runs-on": ubuntu-latest
    strategy:
      matrix:
        level:
          - debug
          - publish
          - verified
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          "node-version": "${{ env.NODE_VERSION }}"
          cache: npm

      - run: npm ci

      - run: npm install -g homey

      - name: Homey App Validation
        run: "homey app validate --level ${{ matrix.level }}"
        env:
          "HOMEY_DEBUG": 1

  "driver_testing":
    needs: setup
    "runs-on": ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          "node-version": "${{ env.NODE_VERSION }}"
          cache: npm

      - run: npm ci

      - run: node scripts/comprehensive-validation-testing.js

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: comprehensive-validation-results/

  build:
    needs:
      - lint_and_test
      - homey_validation
    "runs-on": ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          "node-version": "${{ env.NODE_VERSION }}"
          cache: npm

      - run: npm ci

      - run: npm run build

      - name: Generate matrices
        run: node compatibility-matrix.js

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: "dist/
matrices/
public/"

