# MEGA ULTIMATE ENHANCED - 2025-08-07T16:33:44.912Z
# Workflow amélioré avec liens corrigés et fonctionnalités étendues

name: Tuya Zigbee CI/CD

on:
  push:
    branches: [ master, tuya-light ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Validate Homey app
      uses: homey/homey-app-validate@v1
    - name: Run enrichment scripts
      run: node scripts/core/unified-project-manager.js
    - name: Generate documentation
      run: node scripts/core/documentation-generator.js
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-update: $(date)" || exit 0
        git push