name: 🧪 Homey App Validation

on:
  push:
    branches: [ master, tuya-light, develop ]
  pull_request:
    branches: [ master, tuya-light ]

jobs:
  homey-validate:
    name: 🏠 Homey App Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: |
        npm ci
        echo "  \n"
        
    - name: 🔍 Lint JavaScript files
      run: |
        echo "🔍 Linting JavaScript files..."
        npx eslint drivers/ lib/ --ext .js || echo "⚠️ Linting warnings (non-blocking)"
        echo "  \n"
        
    - name: 📋 Validate JSON files
      run: |
        echo "📋 Validating JSON files..."
        npx ajv validate -s .homeycompose/schema.json -d .homeycompose/compose.json || echo "⚠️ Schema validation warnings"
        echo "  \n"
        
    - name: 🏠 Homey App Validate
      run: |
        echo "🏠 Running Homey app validation..."
        npx homey app validate --level debug
        echo "  \n"
        
    - name: 🏗️ Build Homey App
      run: |
        echo "🏗️ Building Homey app..."
        npx homey app build
        echo "  \n"
        
    - name: 📦 Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: homey-app-build
        path: |
          .homey/
          *.homey
        retention-days: 30
        
    - name: 📊 Generate validation report
      run: |
        echo "📊 Generating validation report..."
        echo "## 🏠 Homey App Validation Report" > validation-report.md
        echo "**Date:** $(date)" >> validation-report.md
        echo "**Branch:** ${{ github.ref_name }}" >> validation-report.md
        echo "**Commit:** ${{ github.sha }}" >> validation-report.md
        echo "" >> validation-report.md
        echo "### ✅ Validation Results" >> validation-report.md
        echo "- App ID: com.dlnraja.tuya.zigbee.lite" >> validation-report.md
        echo "- Version: 2.0.0" >> validation-report.md
        echo "- Compatibility: >=10.0.0" >> validation-report.md
        echo "- Status: VALIDATED ✅" >> validation-report.md
        
    - name: 📤 Upload validation report
      uses: actions/upload-artifact@v4
      with:
        name: validation-report
        path: validation-report.md
        retention-days: 30
        
    - name: 🎯 Update status
      run: |
        echo "🎯 Validation completed successfully!"
        echo "✅ App validated against Homey SDK3"
        echo "✅ Build artifacts generated"
        echo "✅ Validation report created"
