name: 🛡️ Continuous Security Monitoring

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 */6 * * *'  # Toutes les 6 heures

jobs:
  security-monitoring:
    name: 🔍 Security Monitoring
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: 🚨 Block Dangerous Files
      run: |
        echo "🔍 Recherche fichiers dangereux..."
        DANGEROUS_FILES=$(find . -name "id_rsa*" -o -name "*.pem" -o -name "*.key" | grep -v node_modules || true)
        if [ ! -z "$DANGEROUS_FILES" ]; then
          echo "❌ FICHIERS DANGEREUX DÉTECTÉS:"
          echo "$DANGEROUS_FILES"
          exit 1
        fi
        echo "✅ Aucun fichier dangereux"
        
    - name: 🔐 Secret Pattern Detection
      run: |
        echo "🔍 Recherche patterns secrets..."
        if grep -r "BEGIN.*PRIVATE KEY" . --exclude-dir=.git --exclude-dir=node_modules; then
          echo "❌ CLÉ PRIVÉE DÉTECTÉE!"
          exit 1
        fi
        if grep -r "eyJ[A-Za-z0-9+/=]*\.[A-Za-z0-9+/=]*\.[A-Za-z0-9+/=]*" . --exclude-dir=.git --exclude-dir=node_modules; then
          echo "❌ JWT TOKEN DÉTECTÉ!"
          exit 1
        fi
        echo "✅ Aucun pattern secret détecté"
        
    - name: 📊 Security Report
      run: |
        echo "📊 RAPPORT SÉCURITÉ AUTOMATIQUE"
        echo "🗓️ Date: $(date)"
        echo "✅ Scan fichiers dangereux: OK"
        echo "✅ Scan patterns secrets: OK"
        echo "🛡️ Statut: SÉCURISÉ"
        
  auto-cleanup:
    name: 🧹 Auto Cleanup
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      
    - name: 🧹 Emergency Cleanup
      run: |
        echo "🧹 Nettoyage automatique..."
        find . -name "id_rsa*" -delete || true
        find . -name "*.pem" -path "*/test/*" -delete || true
        find . -name "*.key" -path "*/fixtures/*" -delete || true
        echo "✅ Nettoyage terminé"
        
    - name: ✉️ Notification
      if: always()
      run: |
        echo "📧 Notification: Scan sécurité automatique effectué"
        echo "🛡️ Projet maintenu sécurisé"
