name: Continuous Monitoring


# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on:
  schedule:
    - cr
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: '*/30 * * * *'
  workflow_dispatch:

jobs:
  monitor-project:
    runs-
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: ubuntu-latest
    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_VERSION: '18'
        PYTHON_VERSION: '3.11'

    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Statistics
        run: |
          SDK3_COUNT=\
          LEGACY_COUNT=\
          IN_PROGRESS_COUNT=\
          TOTAL_DRIVERS=\
          
          mkdir -p dashboard
          echo "# Dashboard de Monitoring" > dashboard/monitoring.md
          echo "" >> dashboard/monitoring.md
          echo "## Drivers" >> dashboard/monitoring.md
          echo "- Total: \" >> dashboard/monitoring.md
          echo "- SDK3: \" >> dashboard/monitoring.md
          echo "- Legacy: \" >> dashboard/monitoring.md
          echo "- En cours: \" >> dashboard/monitoring.md
          echo "" >> dashboard/monitoring.md
          echo "Date: \" >> dashboard/monitoring.md
          
      - name: Commit Dashboard
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dashboard/monitoring.md
          git commit -m "Dashboard updated - \" || echo "No changes"
          git push

