# Workflow GitHub Actions - cross-platform-git-fix.yml
# Enrichi automatiquement - Mode additif
# Compatible Homey SDK3
# Fonctionnement local prioritaire
# Aucune dépendance API externe
# 
# @author Auto-Enhancement System
# @version Enhanced
# @date 2025-07-26 16:44:49
# Description: Correction cross-platform des auteurs Git
name: Cross-Platform-Git-Fix
on:
  schedule:
    - cron: '0 */6 * * *' # Toutes les 6 heures
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  fix-git-authors:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Récupérer tout l'historique
      
    - name: Setup Git
      run: |
        git config --global user.name "dlnraja"
        git config --global user.email "dylan.rajasekaram@gmail.com"
        
    - name: Fix Git Authors
      run: |
        echo "Correction cross-platform des auteurs Git..."
        
        # Vérifier les commits avec l'ancien email
        OLD_EMAIL="dylan.rajasekaram+myhomeyapp@gmail.com"
        CORRECT_EMAIL="dylan.rajasekaram@gmail.com"
        CORRECT_AUTHOR="dlnraja"
        
        # Réécrire l'historique si nécessaire
        if git log --author="" --oneline | head -1; then
          echo "Commits avec l'ancien email trouvés, réécriture en cours..."
          git filter-branch --env-filter "
            if [ \"\\" = \"\" ]
            then
                export GIT_AUTHOR_EMAIL=\"\"
                export GIT_AUTHOR_NAME=\"\"
            fi
            if [ \"\\" = \"\" ]
            then
                export GIT_COMMITTER_EMAIL=\"\"
                export GIT_COMMITTER_NAME=\"\"
            fi
          " --tag-name-filter cat -- --branches --tags
        else
          echo "Aucun commit avec l'ancien email trouvé"
        fi
        
    - name: Force Push
      run: |
        echo "Force push des changements..."
        git push origin master --force
        
    - name: Success
      run: |
        echo "Correction cross-platform des auteurs Git terminée!"
        echo "Résumé:"
        echo "- Auteurs Git corrigés"
        echo "- Compatible Windows/Linux/macOS"
        echo "- Historique réécrit"
        echo "- Force push effectué"
        
    - name: Clean up package-lock.json
      if: always()
      run: |
        echo "Suppression du package-lock.json pour éviter la surcharge du repo."
        rm -f package-lock.json




