name: 🤖 Enhanced PR and Issue Bot - Intelligent Triage

on:
  schedule:
    - cron: '0 */1 * * *'  # Toutes les heures
    - cron: '0 5 * * *'    # Tous les jours à 5h00
  workflow_dispatch:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

env:
  BOT_NAME: "Tuya Zigbee Bot"
  MAX_ITEMS_PER_RUN: 20
  ENABLE_STATISTICS: true
  ENABLE_LABELS: true
  ENABLE_ASSIGNMENTS: true

jobs:
  # 🔍 ANALYSE INTELLIGENTE
  intelligent-analysis:
    runs-on: ubuntu-latest
    name: 🔍 Analyse intelligente des PR/Issues
    outputs:
      pr-count: ${{ steps.count-prs.outputs.count }}
      issue-count: ${{ steps.count-issues.outputs.count }}
      priority-issues: ${{ steps.priority-check.outputs.count }}
      stale-items: ${{ steps.stale-check.outputs.count }}
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔍 Comptage des PRs ouvertes
        id: count-prs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: prs } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            console.log(`📊 PRs ouvertes: ${prs.length}`);
            core.setOutput('count', prs.length);

      - name: 🔍 Comptage des Issues ouvertes
        id: count-issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            const pureIssues = issues.filter(issue => !issue.pull_request);
            console.log(`📊 Issues ouvertes: ${pureIssues.length}`);
            core.setOutput('count', pureIssues.length);

      - name: 🔍 Vérification des priorités
        id: priority-check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            const priorityIssues = issues.filter(issue => 
              issue.labels.some(label => 
                label.name.toLowerCase().includes('urgent') ||
                label.name.toLowerCase().includes('critical') ||
                label.name.toLowerCase().includes('high')
              )
            );
            console.log(`🚨 Issues prioritaires: ${priorityIssues.length}`);
            core.setOutput('count', priorityIssues.length);

      - name: 🔍 Vérification des éléments obsolètes
        id: stale-check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const now = new Date();
            const staleThreshold = 30; // jours
            
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            
            const staleItems = issues.filter(issue => {
              const createdAt = new Date(issue.created_at);
              const daysSinceCreation = (now - createdAt) / (1000 * 60 * 60 * 24);
              return daysSinceCreation > staleThreshold;
            });
            
            console.log(`⏰ Éléments obsolètes (>${staleThreshold}j): ${staleItems.length}`);
            core.setOutput('count', staleItems.length);

  # 🤖 TRIAGE INTELLIGENT
  intelligent-triage:
    runs-on: ubuntu-latest
    needs: intelligent-analysis
    name: 🤖 Triage intelligent des PR/Issues
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🤖 Traitement des PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const maxItems = parseInt(process.env.MAX_ITEMS_PER_RUN || '20');
            
            console.log(`🤖 Traitement des PRs (max: ${maxItems})`);
            
            const { data: prs } = await github.pulls.list({
              owner, repo, state: 'open', per_page: maxItems
            });
            
            for (const pr of prs) {
              console.log(`📝 Traitement PR #${pr.number}: ${pr.title}`);
              
              // Commentaire automatique
              await github.issues.createComment({
                owner, repo, issue_number: pr.number,
                body: `🤖 **Merci pour votre PR !**\n\n` +
                      `📊 **Analyse automatique:**\n` +
                      `- Titre: ${pr.title}\n` +
                      `- Auteur: @${pr.user.login}\n` +
                      `- Créée: ${new Date(pr.created_at).toLocaleDateString()}\n` +
                      `- Fichiers modifiés: ${pr.changed_files}\n\n` +
                      `🔄 **Prochaines étapes:**\n` +
                      `1. ✅ Vérification automatique\n` +
                      `2. 🔍 Revue par l'équipe\n` +
                      `3. 🚀 Merge si approuvé\n\n` +
                      `*Mode YOLO Intelligent activé - Traitement optimisé*`
              });
              
              // Ajout de labels automatiques
              if (process.env.ENABLE_LABELS === 'true') {
                const labels = [];
                if (pr.title.toLowerCase().includes('fix')) labels.push('bug');
                if (pr.title.toLowerCase().includes('feature')) labels.push('enhancement');
                if (pr.title.toLowerCase().includes('doc')) labels.push('documentation');
                if (pr.changed_files > 10) labels.push('large-change');
                
                if (labels.length > 0) {
                  await github.issues.addLabels({
                    owner, repo, issue_number: pr.number, labels
                  });
                  console.log(`🏷️ Labels ajoutés: ${labels.join(', ')}`);
                }
              }
              
              // Assignation automatique
              if (process.env.ENABLE_ASSIGNMENTS === 'true') {
                const assignees = [];
                if (pr.changed_files > 5) assignees.push('maintainer');
                if (pr.title.toLowerCase().includes('driver')) assignees.push('driver-expert');
                
                if (assignees.length > 0) {
                  await github.issues.addAssignees({
                    owner, repo, issue_number: pr.number, assignees
                  });
                  console.log(`👥 Assignés: ${assignees.join(', ')}`);
                }
              }
            }
            
            console.log(`✅ ${prs.length} PRs traitées`);

      - name: 🤖 Traitement des Issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const maxItems = parseInt(process.env.MAX_ITEMS_PER_RUN || '20');
            
            console.log(`🤖 Traitement des Issues (max: ${maxItems})`);
            
            const { data: issues } = await github.issues.listForRepo({
              owner, repo, state: 'open', per_page: maxItems
            });
            
            const pureIssues = issues.filter(issue => !issue.pull_request);
            
            for (const issue of pureIssues) {
              console.log(`📝 Traitement Issue #${issue.number}: ${issue.title}`);
              
              // Commentaire automatique
              await github.issues.createComment({
                owner, repo, issue_number: issue.number,
                body: `🤖 **Merci pour votre issue !**\n\n` +
                      `📊 **Analyse automatique:**\n` +
                      `- Titre: ${issue.title}\n` +
                      `- Auteur: @${issue.user.login}\n` +
                      `- Créée: ${new Date(issue.created_at).toLocaleDateString()}\n` +
                      `- Labels: ${issue.labels.map(l => l.name).join(', ') || 'Aucun'}\n\n` +
                      `🔄 **Prochaines étapes:**\n` +
                      `1. ✅ Vérification automatique\n` +
                      `2. 🔍 Analyse par l'équipe\n` +
                      `3. 🚀 Résolution prioritaire\n\n` +
                      `*Mode YOLO Intelligent activé - Traitement optimisé*`
              });
              
              // Ajout de labels automatiques
              if (process.env.ENABLE_LABELS === 'true') {
                const labels = [];
                if (issue.title.toLowerCase().includes('bug')) labels.push('bug');
                if (issue.title.toLowerCase().includes('feature')) labels.push('enhancement');
                if (issue.title.toLowerCase().includes('question')) labels.push('question');
                if (issue.title.toLowerCase().includes('driver')) labels.push('driver');
                if (issue.title.toLowerCase().includes('urgent')) labels.push('urgent');
                
                if (labels.length > 0) {
                  await github.issues.addLabels({
                    owner, repo, issue_number: issue.number, labels
                  });
                  console.log(`🏷️ Labels ajoutés: ${labels.join(', ')}`);
                }
              }
              
              // Assignation automatique
              if (process.env.ENABLE_ASSIGNMENTS === 'true') {
                const assignees = [];
                if (issue.title.toLowerCase().includes('driver')) assignees.push('driver-expert');
                if (issue.title.toLowerCase().includes('urgent')) assignees.push('maintainer');
                if (issue.title.toLowerCase().includes('question')) assignees.push('support');
                
                if (assignees.length > 0) {
                  await github.issues.addAssignees({
                    owner, repo, issue_number: issue.number, assignees
                  });
                  console.log(`👥 Assignés: ${assignees.join(', ')}`);
                }
              }
            }
            
            console.log(`✅ ${pureIssues.length} Issues traitées`);

  # 📊 STATISTIQUES ET RAPPORTS
  statistics-report:
    runs-on: ubuntu-latest
    needs: [intelligent-analysis, intelligent-triage]
    name: 📊 Génération des statistiques
    if: env.ENABLE_STATISTICS == 'true'
    steps:
      - name: 📊 Création du rapport
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            const prCount = ${{ needs.intelligent-analysis.outputs.pr-count }};
            const issueCount = ${{ needs.intelligent-analysis.outputs.issue-count }};
            const priorityCount = ${{ needs.intelligent-analysis.outputs.priority-issues }};
            const staleCount = ${{ needs.intelligent-analysis.outputs.stale-items }};
            
            const report = `📊 **RAPPORT TRIAGE INTELLIGENT**\n\n` +
                          `🕐 **Timestamp:** ${new Date().toLocaleString()}\n` +
                          `🤖 **Bot:** ${process.env.BOT_NAME}\n\n` +
                          `📈 **Statistiques:**\n` +
                          `- PRs ouvertes: ${prCount}\n` +
                          `- Issues ouvertes: ${issueCount}\n` +
                          `- Issues prioritaires: ${priorityCount}\n` +
                          `- Éléments obsolètes: ${staleCount}\n\n` +
                          `✅ **Actions effectuées:**\n` +
                          `- Commentaires automatiques ajoutés\n` +
                          `- Labels automatiques appliqués\n` +
                          `- Assignations automatiques effectuées\n` +
                          `- Triage intelligent terminé\n\n` +
                          `🚀 **Mode YOLO Intelligent activé**\n` +
                          `*Workflow optimisé et automatisé*`;
            
            // Créer un commentaire sur une issue de rapport
            const { data: issues } = await github.issues.listForRepo({
              owner, repo, state: 'open', per_page: 1
            });
            
            if (issues.length > 0) {
              await github.issues.createComment({
                owner, repo, issue_number: issues[0].number, body: report
              });
            }
            
            console.log('📊 Rapport de statistiques généré');

  # 🔔 NOTIFICATIONS AVANCÉES
  advanced-notifications:
    runs-on: ubuntu-latest
    needs: intelligent-analysis
    name: 🔔 Notifications avancées
    if: needs.intelligent-analysis.outputs.priority-issues > '0'
    steps:
      - name: 🔔 Notification des priorités
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const priorityCount = ${{ needs.intelligent-analysis.outputs.priority-issues }};
            
            if (priorityCount > 0) {
              const notification = `🚨 **ALERTE PRIORITÉ**\n\n` +
                                 `⚠️ **${priorityCount} issue(s) prioritaire(s) détectée(s)**\n\n` +
                                 `🔍 **Action requise:** Vérification immédiate\n` +
                                 `⏰ **Timestamp:** ${new Date().toLocaleString()}\n\n` +
                                 `*Mode YOLO Intelligent - Alerte automatique*`;
              
              // Créer une issue d'alerte
              await github.issues.create({
                owner, repo,
                title: `🚨 ALERTE: ${priorityCount} issue(s) prioritaire(s)`,
                body: notification,
                labels: ['urgent', 'alert', 'priority']
              });
              
              console.log(`🚨 Alerte créée pour ${priorityCount} issue(s) prioritaire(s)`);
            } 
