# gen-env-tokens.yml
# Description: Workflow automatisé pour gen env tokens
# Date: 2025-07-25
# Version: 1.0

name: Generate ENV with GitHub Tokens


# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on:
  workflow_dispatch:

jobs:
  generate_env:
    runs-
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: ubuntu-latest
    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || secrets.FULLTOKEN }}
      
      - name: Generate .env with tokens
        run: |
          echo "GH_PAT=${{ secrets.GH_PAT }}" > .env.tokens
          echo "FULLTOKEN=${{ secrets.FULLTOKEN }}" >> .env.tokens

      - name: Commit and push .env.tokens
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "github-actions-bot@noreply.github.com"
          git add .env.tokens
          git commit -m "ci: generate .env.tokens with both GH_PAT and FULLTOKEN" || echo "No changes"
          git push

