name: Homey App Store Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  homey-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install Homey CLI
      run: |
        npm install -g homey
        homey --version
        
    - name: Clean and prepare
      run: |
        rm -rf .homeycompose node_modules || true
        echo "🧹 Clean build environment prepared"
        
    - name: Validate App
      run: |
        echo "🔍 Validating Homey app..."
        homey app validate
        
    - name: Update version
      run: |
        echo "📝 Auto-incrementing version..."
        node -e "
        const fs = require('fs');
        const app = JSON.parse(fs.readFileSync('app.json', 'utf8'));
        const parts = app.version.split('.');
        parts[2] = String(parseInt(parts[2] || 0) + 1);
        app.version = parts.join('.');
        fs.writeFileSync('app.json', JSON.stringify(app, null, 2));
        console.log('New version:', app.version);
        "
        
    - name: Login to Homey
      run: |
        echo "🔐 Logging into Homey..."
        homey login --token ${{ secrets.HOMEY_TOKEN }}
        
    - name: Publish to Homey App Store
      run: |
        echo "🚀 Publishing to Homey App Store..."
        homey app publish --changelog "🏪 Professional Tuya Zigbee Support - Complete manufacturer ID compliance, enhanced device support, optimized for Homey App Store standards"
        
    - name: Commit version bump
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add app.json
        git commit -m "🔖 Version bump for Homey App Store" || exit 0
        git push
