name: Homey App Store Publish - Fixed Auth

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  homey-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Homey CLI
      run: |
        npm install -g @athombv/homey-cli
        homey --version
        
    - name: Clean environment
      run: |
        rm -rf .homeycompose node_modules || true
        echo "🧹 Environment cleaned"
        
    - name: Validate App
      run: |
        echo "🔍 Validating Homey app..."
        homey app validate
        
    - name: Update version
      run: |
        echo "📝 Auto-incrementing version..."
        node -e "
        const fs = require('fs');
        const app = JSON.parse(fs.readFileSync('app.json', 'utf8'));
        const parts = app.version.split('.');
        parts[2] = String(parseInt(parts[2] || 0) + 1);
        app.version = parts.join('.');
        fs.writeFileSync('app.json', JSON.stringify(app, null, 2));
        console.log('✅ New version:', app.version);
        "
        
    - name: Login to Homey (Fixed Auth)
      env:
        HOMEY_TOKEN: ${{ secrets.HOMEY_TOKEN }}
      run: |
        echo "🔐 Logging into Homey with corrected auth..."
        if [ -z "$HOMEY_TOKEN" ]; then
          echo "❌ HOMEY_TOKEN is not set!"
          exit 1
        fi
        echo "$HOMEY_TOKEN" | homey login
        
    - name: Publish to Homey App Store
      run: |
        echo "🚀 Publishing Ultimate Zigbee Hub to Homey App Store..."
        homey app publish --changelog "🎯 Ultimate Zigbee Hub v2.0+ - Enhanced with 164 drivers, comprehensive manufacturer support, UNBRANDED professional structure, full SDK3 compliance"
        
    - name: Commit version bump
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Auto-Publish"
        git add app.json
        git commit -m "🔖 Version auto-increment for Homey App Store" || exit 0
        git push
        
    - name: Success notification
      run: |
        echo "🎉 PUBLICATION RÉUSSIE!"
        echo "📱 Dashboard: https://tools.developer.homey.app/apps/app/com.dlnraja.ultimate.zigbee.hub"
