name: Homey Publication

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Homey CLI (try multiple packages)
      run: |
        echo "🔍 Trying Homey CLI installation..."
        npm install -g homey || npm install -g athom-cli || npm install -g @athombv/cli || echo "CLI installation failed, continuing..."
        
    - name: Clean environment
      run: |
        rm -rf .homeycompose node_modules docs/ public/ _site/ || true
        echo "🧹 Environment cleaned"
        
    - name: Validate App (if CLI available)
      run: |
        if command -v homey &> /dev/null; then
          echo "🔍 Validating with homey CLI..."
          homey app validate
        elif command -v athom &> /dev/null; then
          echo "🔍 Validating with athom CLI..."
          athom app validate
        else
          echo "⚠️ No CLI available, skipping validation"
        fi
        
    - name: Publish to Homey App Store
      env:
        HOMEY_TOKEN: ${{ secrets.HOMEY_TOKEN }}
      run: |
        echo "🚀 Publishing Ultimate Zigbee Hub..."
        if [ -z "$HOMEY_TOKEN" ]; then
          echo "❌ HOMEY_TOKEN not configured!"
          exit 1
        fi
        
        if command -v homey &> /dev/null; then
          echo "📱 Using homey CLI..."
          echo "$HOMEY_TOKEN" | homey login
          homey app publish
        elif command -v athom &> /dev/null; then
          echo "📱 Using athom CLI..."
          echo "$HOMEY_TOKEN" | athom login
          athom app publish
        else
          echo "❌ No CLI available for publication"
          exit 1
        fi
        
    - name: Success Report
      run: |
        echo "🎉 PUBLICATION COMPLETED!"
        echo "📱 App: Ultimate Zigbee Hub - Professional Edition"
        echo "🔗 Dashboard: https://tools.developer.homey.app/apps/app/com.dlnraja.ultimate.zigbee.hub"
