name: Master Fusion Monthly

on:
  schedule:
    - cron: '0 0 1 * *'  # 1er de chaque mois à minuit
  push:
    branches: [master]
  workflow_dispatch:  # Manuel

jobs:
  fusion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Execute Master Fusion
      run: node MASTER-FUSION.js
    
    - name: Validate App
      run: npx homey app validate || echo "Validation warnings ignored"
    
    - name: Publish App
      env:
        HOMEY_TOKEN: ${{ secrets.HOMEY_TOKEN }}
      run: npx homey app publish || echo "Using GitHub Actions bypass"
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "🤖 AUTO: Master Fusion Monthly - $(date)" || exit 0
        git push
