name: Monthly Driver Update

on:
  schedule:
    - cron: '0 0 1 * *'  # Run on the 1st of every month at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-drivers:
    name: Update and Test Drivers
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed for git diff

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm install -g homey@latest

    - name: Check for updates from upstream repositories
      id: check-updates
      run: |
        # Add upstream repositories
        git remote add upstream-zb https://github.com/JohanBendz/com.tuya.zigbee.git || true
        git fetch upstream-zb
        
        # Check for changes in drivers directory
        if ! git diff --quiet HEAD upstream-zb/main -- drivers/; then
          echo "DRIVER_UPDATES=true" >> $GITHUB_ENV
          echo "UPDATES_FOUND=true" >> $GITHUB_OUTPUT
        else
          echo "DRIVER_UPDATES=false" >> $GITHUB_ENV
          echo "UPDATES_FOUND=false" >> $GITHUB_OUTPUT
        fi

    - name: Create update branch
      if: steps.check-updates.outputs.UPDATES_FOUND == 'true'
      run: |
        git config --global user.name "Tuya Bot"
        git config --global user.email "tuya-bot@noreply.github.com"
        git checkout -b driver-update/$(date +%Y-%m-%d)

    - name: Merge updates
      if: steps.check-updates.outputs.UPDATES_FOUND == 'true'
      run: |
        git merge --no-commit --allow-unrelated-histories upstream-zb/main
        git checkout HEAD -- package*.json
        git checkout HEAD -- .github/
        git add .
        git commit -m "Merge upstream driver updates" || echo "No changes to commit"

    - name: Run tests
      if: steps.check-updates.outputs.UPDATES_FOUND == 'true'
      run: |
        # Run validation and tests
        npm run validate
        npm test

    - name: Create Pull Request
      if: steps.check-updates.outputs.UPDATES_FOUND == 'true' && github.event_name == 'schedule'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: monthly driver updates"
        title: "[AUTO] Monthly Driver Updates - $(date +'%Y-%m-%d')"
        body: |
          Automated monthly driver updates from upstream sources.
          
          ### Changes Detected:
          - Updated drivers from upstream repositories
          - Validated against Homey SDK3
          
          ### Testing Status:
          - [x] Automated tests passed
          - [ ] Manual testing required
          
          ### Notes:
          This is an automated PR. Please review the changes before merging.
        branch: driver-update/$(date +%Y-%m-%d)
        base: main
        delete-branch: true

    - name: Create Issue if Updates Found
      if: steps.check-updates.outputs.UPDATES_FOUND == 'true' && github.event_name == 'workflow_dispatch'
      uses: actions/github-script@v6
      with:
        script: |
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'driver-update'
          });
          
          if (issues.length === 0) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Driver Updates] Review Required - ${new Date().toISOString().split('T')[0]}`,
              body: `Driver updates have been detected and tested. Please review the changes in branch driver-update/${new Date().toISOString().split('T')[0]}`,
              labels: ['driver-update', 'needs-review']
            });
          }

    - name: No updates found
      if: steps.check-updates.outputs.UPDATES_FOUND == 'false'
      run: echo "No driver updates found in upstream repositories."
