name: Monthly Zigbee Referential Update

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update-referential:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - run: npm ci
    - run: node scripts/update-zigbee-referential.js
    - run: node scripts/generate-device-templates.js
    - run: node scripts/update-documentation.js
