name: Monthly Device Database Update
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  update-devices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run forum analyzer
        run: node dev-tools/automation/forum-source-analyzer.js
        
      - name: Validate app
        run: npx homey app validate --level publish
        
      - name: Commit updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Monthly device database update" || exit 0
          git push