# mounthly-backup.yml
# Description: Workflow automatisé pour mounthly backup
# Date: 2025-07-25
# Version: 1.0

name: Monthly backup ZIP

# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on:
  schedule:
    - cr
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: '0 1 1 * *'
  workflow_dispatch:
jobs:
  backup:
    runs-
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: ubuntu-latest
    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_VERSION: '18'
        PYTHON_VERSION: '3.11'

    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/checkout@v4
      - name: Create zip
        run: |
          zip -r repo_backup_$(date +%Y%m%d).zip .
      - uses: actions/upload-artifact@v4
        with:
          name: monthly-backup
          path: repo_backup_*.zip

