name: Fallback - pr-issue-bot
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  fallback-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Validate
      run: echo 'Fallback workflow executed'



