name: Homey App Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update version
      uses: athombv/github-action-homey-app-update-version@v1
      with:
        path: .
        version: ${{ github.event.release.tag_name }}
    
    - name: Publish to Homey App Store
      uses: athombv/github-action-homey-app-publish@v1
      with:
        path: .
        email: ${{ secrets.HOMEY_EMAIL }}
        password: ${{ secrets.HOMEY_PASSWORD }}
