name: Release Tuya Light
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 4 1 * *'  # Monthly sync
  workflow_dispatch:  # Manual trigger

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Validate Homey SDK
        run: |
          npm install -g homey
          homey app validate
      
      - name: Create tuya-light branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b tuya-light || git checkout tuya-light
          git reset --hard master
      
      - name: Clean tuya-light branch
        run: |
          # Remove AI/automation files for lite version
          rm -rf tools/ai-*.js
          rm -rf tools/generate-*.js
          rm -rf scripts/*.ps1
          rm -rf .cursor/
          rm -rf logs/
          rm -rf backups/
          rm -rf cursor_*.md
          rm -rf TODO_*.md
          rm -rf *.ps1
          rm -rf *.sh
          # Keep only essential files
          find . -name "*.log" -delete
          find . -name "*.tmp" -delete
          find . -name "cursor_temp*" -delete
      
      - name: Create release ZIP
        run: |
          zip -r tuya-light.zip . \
            -x "*.git*" \
            -x "*.github*" \
            -x "node_modules/*" \
            -x "tools/ai-*.js" \
            -x "scripts/*.ps1" \
            -x ".cursor/*" \
            -x "logs/*" \
            -x "backups/*" \
            -x "cursor_*.md" \
            -x "TODO_*.md" \
            -x "*.ps1" \
            -x "*.sh" \
            -x "*.log" \
            -x "*.tmp" \
            -x "cursor_temp*"
      
      - name: Update tuya-light branch
        run: |
          git add .
          git commit -m "feat(release): Update tuya-light branch // FR: Mise à jour de la branche tuya-light" || true
          git push origin tuya-light --force
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: tuya-light.zip
          tag_name: tuya-light-v${{ github.run_number }}
          name: Tuya Light Release v${{ github.run_number }}
          body: |
            ## Tuya Light Release
            
            **Version:** ${{ github.run_number }}
            **Date:** $(date +'%Y-%m-%d %H:%M:%S')
            **Branch:** tuya-light
            
            ### Changes
            - Cleaned version without AI/automation
            - Homey SDK3 compatible
            - Essential drivers only
            - Ready for immediate installation
            
            ### Installation
            ```bash
            homey app install tuya-light.zip
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Sync to tuya-light-repo
        run: |
          # Clone tuya-light-repo if exists
          git clone https://github.com/dlnraja/tuya-light-repo.git tuya-light-repo || true
          cd tuya-light-repo
          cp ../tuya-light.zip .
          git add .
          git commit -m "feat(sync): Sync from tuya-light branch // FR: Synchronisation depuis la branche tuya-light" || true
          git push origin main
