name: Monthly Scraping

on:
  schedule:
    - cron: '0 3 * * 1'  # Tous les lundis à 3h UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run scraping
        run: node scripts/scrape_homey_threads.mjs

      - name: Commit and push changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/SOURCES.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update SOURCES.md" && git push)
