name: 🔐 Security Scanner & Protection

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 2 * * *'  # Tous les jours à 2h

jobs:
  security-scan:
    name: 🛡️ Security Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: 🔍 Secret Detection with GitLeaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 🔐 TruffleHog Secrets Scanner
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        
    - name: 🛡️ Dependency Security Audit
      run: |
        npm audit --audit-level high
        npm audit fix --force
        
    - name: 🚨 Remove Dangerous Files
      run: |
        echo "🔍 Recherche de fichiers dangereux..."
        find . -name "id_rsa*" -delete
        find . -name "*.pem" -delete
        find . -name "*.key" -path "*/test/*" -delete
        find . -name "*.p12" -delete
        find . -name ".env*" -path "*/node_modules/*" -delete
        echo "✅ Nettoyage sécurité terminé"
        
    - name: 🔒 Validate No Secrets in Commit
      run: |
        echo "🔍 Vérification finale..."
        if grep -r "BEGIN.*PRIVATE KEY" . --exclude-dir=.git --exclude-dir=node_modules; then
          echo "❌ ERREUR: Clé privée détectée!"
          exit 1
        fi
        echo "✅ Aucun secret détecté"
        
    - name: 📊 Security Report
      if: always()
      run: |
        echo "📊 RAPPORT SÉCURITÉ - $(date)"
        echo "✅ Scan GitLeaks: Terminé"
        echo "✅ Scan TruffleHog: Terminé" 
        echo "✅ Audit dépendances: Terminé"
        echo "✅ Nettoyage fichiers: Terminé"
        echo "🛡️ Niveau sécurité: MAXIMAL"
