# sync-rebuild.yml
# Description: Workflow automatisé pour sync rebuild
# Date: 2025-07-25
# Version: 1.0

name: Sync master to rebuild/ai-bootstrap


# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on:
  schedule:
    - cr
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: '30 4 1 * *'

jobs:
  sync:
    runs-
# Permissions pour la sécurité
permissions:
  contents: read
  pull-requests: read
  issues: read
  actions: read
  security-events: read

on: ubuntu-latest
    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_VERSION: '18'
        PYTHON_VERSION: '3.11'

    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Pousser vers rebuild/ai-bootstrap
        run: |
          git checkout -B rebuild/ai-bootstrap
          git push origin rebuild/ai-bootstrap --force

