# MEGA ULTIMATE ENHANCED - 2025-08-07T16:33:44.965Z
# Workflow amélioré avec liens corrigés et fonctionnalités étendues

name: 🔧 Validate App Structure

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 2 * * *'  # Tous les jours à 2h du matin

jobs:
  validate-app-structure:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm install
      
    - name: 🔍 Fix App Structure
      run: npm run fix-app-structure
      
    - name: 🏠 Validate Homey CLI (if available)
      run: |
        if command -v homey > /dev/null; then
          npm run validate-homey-cli
        else
          echo "Homey CLI not installed in CI environment"
          echo "This is expected - CLI validation will be done locally"
        fi
        
    - name: 📊 Generate validation report
      run: |
        echo "## App Structure Validation Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ✅ Structure Check" >> $GITHUB_STEP_SUMMARY
        echo "- app.json: $(test -f app.json && echo '✅ Present' || echo '❌ Missing')" >> $GITHUB_STEP_SUMMARY
        echo "- app.js: $(test -f app.js && echo '✅ Present' || echo '❌ Missing')" >> $GITHUB_STEP_SUMMARY
        echo "- drivers/: $(test -d drivers && echo '✅ Present' || echo '❌ Missing')" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📁 Directory Structure" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        find . -type f -name "*.json" -o -name "*.js" | head -20 >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        
    - name: 🚀 Commit fixes (if any)
      if: success()
      run: |
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "🔧 Auto-fix app structure [skip ci]"
          git push
        fi
        
    - name: 📋 Upload validation artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: validation-results
        path: |
          logs/
          data/
          *.log
        retention-days: 7 