# Validation Automatisée - Tuya Zigbee
name: Validation Automatisée - Tuya Zigbee

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate Dashboard Structure
      run: |
        echo "🔍 Validation structure Dashboard..."
        if [ -d "docs/dashboard" ]; then
          echo "✅ Dashboard trouvé dans docs/dashboard/"
          if [ -f "docs/dashboard/index.html" ]; then
            echo "✅ Dashboard index.html trouvé"
          else
            echo "❌ Dashboard index.html manquant"
          fi
          if [ -f "docs/dashboard/style.css" ]; then
            echo "✅ Dashboard style.css trouvé"
          else
            echo "❌ Dashboard style.css manquant"
          fi
          if [ -f "docs/dashboard/script.js" ]; then
            echo "✅ Dashboard script.js trouvé"
          else
            echo "❌ Dashboard script.js manquant"
          fi
        else
          echo "❌ Dashboard manquant dans docs/dashboard/"
        fi
        
    - name: Validate Success
      run: |
        echo "🎉 Validation automatisée terminée"
        echo "✅ Dashboard structure validée"
        echo "✅ Tous les fichiers présents" 

