# MEGA ULTIMATE ENHANCED - 2025-08-07T16:33:44.980Z
# Workflow amélioré avec liens corrigés et fonctionnalités étendues

name: 🔧 Validate Tuya Zigbee Drivers

on:
  push:
    paths:
      - 'drivers/**'
  pull_request:
    paths:
      - 'drivers/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Validate driver.compose.json files
        run: |
          find drivers -name 'driver.compose.json' | while read file; do
            echo "🔍 Validating $file"
            if ! jq empty "$file"; then
              echo "❌ Invalid JSON in $file"
              exit 1
            fi
          done
          echo "✅ All driver.compose.json files are valid."

      - name: Validate driver.js presence
        run: |
          MISSING=$(find drivers -type d ! -exec test -e "{}/driver.js" \; -print)
          if [ -n "$MISSING" ]; then
            echo "❌ Missing driver.js in:"
            echo "$MISSING"
            exit 1
          fi
          echo "✅ All driver.js files are present."

      - name: Generate drivers matrix
        run: |
          node scripts/generate-matrix.js
          echo "📊 Drivers matrix generated successfully"

      - name: Upload matrix artifact
        uses: actions/upload-artifact@v3
        with:
          name: drivers-matrix
          path: |
            drivers-matrix.md
            drivers-matrix.html
