# YOLO Mode - Exécution Automatique Avancée
name: YOLO Mode - Tuya Zigbee

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Toutes les 30 minutes

jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: YOLO Dashboard Check
      run: |
        echo "🚀 YOLO Mode - Dashboard Check..."
        if [ -d "docs/dashboard" ]; then
          echo "✅ Dashboard trouvé dans docs/dashboard/"
          echo "📊 Dashboard accessible via: docs/dashboard/index.html"
        else
          echo "❌ Dashboard manquant dans docs/dashboard/"
        fi
        
    - name: YOLO Success
      run: |
        echo "🎉 YOLO Mode terminé"
        echo "✅ Dashboard validé"
        echo "✅ Exécution automatique réussie" 

